import type { Metadata } from "next";
import { pageTitleAndDescription } from "@/lib/page-title";
import { LegalLayout } from "@/components/legal/legal-layout";
import { LegalSection } from "@/components/legal/legal-section";

export function generateMetadata(): Promise<Metadata> {
  return pageTitleAndDescription(
    "landing.footer.acceptableUse",
    "pageTitle.acceptableUseDescription"
  );
}

/**
 * The acceptable use policy. Same convention as /terms and /privacy:
 * hardcoded English, and LegalLayout's `draft` banner states plainly
 * that this is not yet reviewed legal copy — which, unlike
 * /ai-transparency, it genuinely is.
 *
 * WHAT CHANGED FROM THE 2026-08-08 DRAFT, which was written and never
 * merged. Checked against main on 2026-09-02:
 *
 *   "generated websites, presentations, documents, agents and emails"
 *   — PRESENTATIONS DO NOT GENERATE. lib/build-modules.ts renamed the
 *   module to "Presentation notes" precisely because the old name
 *   promised a generator that does not exist. Listing it as a thing
 *   this policy governs the output of would have been a promise made in
 *   the enforcement policy, which is a strange place to make one.
 *
 *   "subject to an automated safety review before going live; a page
 *   that fails review is not published" — TRUE, but it conflated two
 *   checks with opposite failure modes, and the difference decides what
 *   a user can actually expect. lib/website-security-review.ts is a
 *   model call that DEFAULTS TO SAFE on any error; it does not block.
 *   lib/website-html-security-scan.ts is deterministic, fail-closed at
 *   publish, and is what actually refuses a page. Section 3 now
 *   separates them, because "we review your site" and "we will not serve
 *   a page carrying an external script" are different commitments and
 *   only the second is one we keep unconditionally.
 *
 *   "evade the daily platform spend cap" — kept. Verified:
 *   lib/ai-circuit-breaker.ts's checkDailyPlatformCap() is real and
 *   reads daily_ai_spend_tracking.
 */
export default function AcceptableUsePage() {
  return (
    <LegalLayout titleKey="landing.footer.acceptableUse" updated="2026-09-02">
      <LegalSection title="1. The short version">
        <p>
          Use Ionexa to run your own work. Don&apos;t use it to harm people, break laws,
          deceive, or abuse the platform. We remove content and suspend accounts that do.
        </p>
      </LegalSection>

      <LegalSection title="2. Prohibited content and conduct">
        <p>
          You may not use Ionexa — including generated websites, documents, research
          reports, code, agents, and emails sent on your behalf — to: publish or distribute
          illegal content; harass, defame or threaten; generate deceptive content that
          impersonates real people or organisations; distribute malware or phishing pages;
          infringe intellectual property; publish content sexualising minors (zero
          tolerance, reported where required by law); send spam or scrape at abusive volume;
          or attempt to bypass usage metering, rate limits or the safety checks described
          below.
        </p>
      </LegalSection>

      <LegalSection title="3. Published sites specifically">
        <p>
          Published websites are served from our infrastructure, from our domain, to
          strangers. Two different things run on them, and it is worth being precise about
          which one is a promise.
        </p>
        <p>
          <strong>The one that blocks.</strong> Every publish runs a deterministic scan of
          the HTML, and it fails closed. A page carrying an external script, an inline event
          handler, a form posting to a third-party server, an iframe from a host not on our
          list, or dynamic code execution is <em>not published</em>, and the reasons are
          shown to you. That check has no discretion and cannot be waived.
        </p>
        <p>
          <strong>The one that advises.</strong> At generation and edit time a model also
          reviews the page for phishing, impersonation and fraud. It is a second opinion, it
          errs towards allowing, and if it fails for any technical reason your page still
          proceeds. Passing it is not our endorsement of your content and does not shift
          responsibility for that content away from you.
        </p>
        <p>
          Neither check judges whether your claims are true. That remains yours.
        </p>
      </LegalSection>

      <LegalSection title="4. Agents specifically">
        <p>
          Agents act on schedules you set. You are responsible for what they do and what
          they send, including to people who did not ask to hear from you. Their output
          always discloses that it was generated by an AI agent, in the language the agent
          writes in — that disclosure is not optional and may not be removed or suppressed.
        </p>
      </LegalSection>

      <LegalSection title="5. Fair use of AI capacity">
        <p>
          Credits meter normal use. Deliberately structuring requests to exhaust platform
          capacity, to evade the platform-wide daily cap on AI calls, or to resell raw model
          access through your account is not permitted.
        </p>
      </LegalSection>

      <LegalSection title="6. Enforcement">
        <p>
          We may remove content, pause publishing, disable agents, or suspend accounts that
          violate this policy — proportionate to the violation, with notice where lawful.
          Report abuse through the contact page; reports are read by a person.
        </p>
        <p>
          What the AI itself does, which models run and what they are given, is described
          separately on the AI transparency page.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
