/**
 * THE GLOBE, DEFINED ONCE.
 *
 * Ionexa had two marks. The backdrop (components/auth/auth-background.tsx)
 * is a wireframe globe: a sphere with latitude and meridian ellipses. The
 * favicon, the apple icon and the email logo were a different drawing —
 * a ring with a tilted orbit and a node — and the ThinkingIndicator was a
 * third thing again, a three-node constellation borrowed from
 * NetworkField. Three shapes, one product.
 *
 * This is the one shape, and it is DATA rather than markup so that every
 * surface can be derived from it instead of re-drawn beside it:
 *
 *   src/components/ui/globe-mark.tsx   the React component (thinking,
 *                                      loading, empty states)
 *   src/app/icon.svg                   generated by scripts/generate-icons.mjs
 *   src/app/favicon.ico, apple-icon.png        same generator
 *   public/ionexa-email-logo.png       scripts/generate-email-logo.mjs
 *
 * THE SERIALISER LIVES NEXT DOOR, in globe-svg.ts, and the split is not
 * tidiness: globeSvg() writes SVG documents for the icon and email-logo
 * generators and no browser ever calls it. Leaving it here put it one
 * import away from every page that renders a loading state, on the hope
 * that tree-shaking would notice. This file is geometry, and geometry is
 * all the client needs.
 *
 * scripts/tests/globe-mark.test.mjs asserts each of those matches what
 * this file produces, so the shapes cannot drift apart again by anyone
 * editing one of them.
 *
 * ---------------------------------------------------------------------
 * WHY THE SILHOUETTE IS THE OLD FAVICON'S AND NOT THE BACKDROP'S.
 * ---------------------------------------------------------------------
 * A favicon is consumed at 16px. The backdrop globe has five latitude
 * bands and six meridians; at 16px those are eleven sub-pixel strokes
 * inside a six-pixel circle, which is a grey smudge, and the brand would
 * have been thrown away to get there. The old favicon already WAS a globe
 * — sphere, tilted orbit, node — so that is the canonical mark, and the
 * backdrop's density is what "full" detail adds on top of it. The
 * silhouette and the orbit are identical at every size; only the interior
 * bands appear as there is room for them.
 *
 * Co-ordinates are normalised to a 0 0 100 100 viewBox. They are the old
 * favicon's, transformed once: it drew in a "270 95 140 140" box, so
 * (v - origin) * 100/140 — e.g. its r=42 sphere becomes r=30 here.
 */

export const GLOBE_VIEW = 100;
export const GLOBE_CENTRE = GLOBE_VIEW / 2;

/** `mark` is the 16px-legible core. `full` adds the backdrop's interior
 *  bands, which need roughly 32px before they stop being noise. */
export type GlobeDetail = "mark" | "full";

export type GlobeShape =
  | {
      kind: "circle";
      role: "sphere" | "node";
      cx: number;
      cy: number;
      r: number;
      /** Multiplier on the caller's base stroke width. `null` means the
       *  shape is filled rather than stroked. */
      stroke: number | null;
      opacity: number;
    }
  | {
      kind: "ellipse";
      role: "orbit" | "latitude" | "meridian";
      cx: number;
      cy: number;
      rx: number;
      ry: number;
      rotate: number;
      stroke: number;
      opacity: number;
    };

const C = GLOBE_CENTRE;

/** The sphere. Always drawn, at every size — it is the silhouette. */
const SPHERE: GlobeShape = { kind: "circle", role: "sphere", cx: C, cy: C, r: 30, stroke: 1, opacity: 1 };

/** The tilted orbit that crosses outside the sphere. This is the part
 *  that reads as "a world with something going around it" rather than as
 *  a plain circle, so it is in the mark, not in the detail. */
const ORBIT: GlobeShape = {
  kind: "ellipse",
  role: "orbit",
  cx: C,
  cy: C,
  rx: 42.86,
  ry: 15.71,
  rotate: -20,
  stroke: 0.67,
  opacity: 0.5,
};

/** The node on the orbit. Filled, not stroked: at 16px a stroked ring of
 *  this size closes up into a dot anyway, and a fill is the same pixels
 *  with none of the ambiguity. */
const NODE: GlobeShape = { kind: "circle", role: "node", cx: C, cy: 20, r: 4.29, stroke: null, opacity: 1 };

/** The backdrop's interior, reduced to the two bands that survive being
 *  small: one latitude and one meridian. Adding the other nine makes a
 *  denser globe at 140vmin and a grey disc at 32px. */
const LATITUDE: GlobeShape = {
  kind: "ellipse",
  role: "latitude",
  cx: C,
  cy: C,
  rx: 30,
  ry: 10.5,
  rotate: 0,
  stroke: 0.5,
  opacity: 0.55,
};
const MERIDIAN: GlobeShape = {
  kind: "ellipse",
  role: "meridian",
  cx: C,
  cy: C,
  rx: 11,
  ry: 30,
  rotate: 0,
  stroke: 0.5,
  opacity: 0.55,
};

/**
 * The shapes, in PAINT ORDER: interior bands first, then the sphere over
 * them, then the orbit, then the node on top.
 *
 * THIS COMMENT USED TO CLAIM THE ORDER MATTERED VISUALLY — that a node
 * painted under the orbit line would read as a bead on a wire. It was
 * measured and it is not true, so it is corrected here rather than left
 * to be believed:
 *   · the nearest point of the orbit's centreline is 12.89 units from the
 *     node's centre; minus the node's 4.29 radius and the orbit's 1.07
 *     half-stroke, they clear each other by 7.53 units and never touch.
 *   · every shape is drawn in one colour, so compositing any over any
 *     other changes nothing. Rasterised at 512px in both orders, with the
 *     node's glow applied: 0 of 1,048,576 subpixels differed.
 * The order is kept because it is the order a person would draw it in and
 * because it would start to matter the moment a second colour or a
 * partial alpha enters the mark — not because it is currently visible.
 */
export function globeShapes(detail: GlobeDetail = "mark"): GlobeShape[] {
  return detail === "full" ? [LATITUDE, MERIDIAN, SPHERE, ORBIT, NODE] : [SPHERE, ORBIT, NODE];
}

/** The shapes that spin as one group — everything except the sphere and
 *  its interior, which are rotationally symmetric and would look static
 *  no matter what. Spinning only these is also less to repaint. */
export function orbitingRoles(): GlobeShape["role"][] {
  return ["orbit", "node"];
}

/** Below this, a filled dot stops reading as a bead and starts reading as
 *  antialiasing on the ring it sits on. Measured by hit-testing the
 *  painted extent in Chromium, in globe-mark.prodtest.mjs. */
const MIN_NODE_PX = 4;

/** The node is 4.29 units across the radius of a 100-unit box, so its
 *  drawn diameter in CSS pixels is this fraction of the rendered size. */
const NODE_DIAMETER_FRACTION = (NODE.r * 2) / GLOBE_VIEW;

/** A bead cannot grow past a third of the sphere's radius without turning
 *  the mark into a comet. At 18px the raw rule asks for 2.59; this is
 *  what stops it. */
const MAX_NODE_SCALE = 2.5;

/**
 * How much to enlarge the node at a given rendered size.
 *
 * THIS EXISTS BECAUSE THE FIRST FIX WAS HALF A FIX. The 16px favicon came
 * out as a smudge during this work; the node was scaled up in the SVG
 * generator and the icons were correct after that. The React component
 * never got the same treatment, so the two sizes the ThinkingIndicator
 * actually ships — 18px inside the Ask button, 26px beside body copy,
 * between them the most-seen instances of the mark in the product — drew
 * the node at its raw radius. Hit-testing the painted extent in Chromium
 * measured 1.75px across at 18px. A 1.75px dot on top of a 0.58px ring
 * stroke is not a bead.
 *
 * Optical compensation, so the proportions are DELIBERATELY not constant
 * across sizes: at 80px this returns 1 and the drawing is the drawing.
 *
 * The raster generators pass their own values instead of using this. That
 * is not duplication — downscaling a rasterised PNG to 16px destroys thin
 * features in a way CSS rendering does not, so those need more, and
 * scripts/generate-icons.mjs says so where it sets them.
 */
export function nodeScaleFor(size: number): number {
  const drawnPx = NODE_DIAMETER_FRACTION * size;
  if (drawnPx >= MIN_NODE_PX) return 1;
  return Math.min(MAX_NODE_SCALE, MIN_NODE_PX / drawnPx);
}
