import type { Metadata } from "next";
import { LegalLayout } from "@/components/legal/legal-layout";
import { LegalSection } from "@/components/legal/legal-section";

export const metadata: Metadata = {
  title: "AI Transparency",
  description: "Which AI models Ionexa uses, what they do, and what data they see.",
};

/**
 * EU AI Act, Article 50 — the transparency page (V3 Task 15). Plain
 * statements of which models run, what each feature does with them, and
 * what data they see. Hardcoded English, same as the other legal pages;
 * a translated summary of the in-product behaviour lives in the product
 * itself, which is fully localised.
 */
export default function AiTransparencyPage() {
  return (
    <LegalLayout title="ai_transparency" updated="2026-08-08">
      <LegalSection title="1. You are interacting with an AI system">
        <p>
          Ionexa AI is built around large language models. Every feature that generates,
          classifies, summarises, plans or analyses content does so by calling an AI model.
          Interfaces where you interact with AI carry an inline notice, and this page is the
          full statement behind that notice, as required by Article 50 of the EU AI Act
          (in application since 2 August 2026).
        </p>
      </LegalSection>

      <LegalSection title="2. Which models run">
        <p>
          Ionexa uses Anthropic&apos;s Claude model family via the Anthropic API. Different
          features use different model tiers (faster models for classification and support
          answers, more capable models for websites, research and presentations); the exact
          model that ran is recorded with every action and shown in your usage history in
          Settings, and in each research report&apos;s &quot;How this was made&quot; panel.
        </p>
      </LegalSection>

      <LegalSection title="3. What each feature does with AI">
        <p>
          <strong>Chat &amp; Create</strong>: your message, relevant workspace context and
          conversation history are sent to the model to produce the reply or classify the
          entry. <strong>Website Builder</strong>: your description (and optional reference
          images) generate a complete web page; a safety review pass checks the output.
          <strong> Deep Research</strong>: the model runs web searches and writes a sourced
          report; every figure links to a real source. <strong>Presentations</strong>: the
          model researches and writes slides with cited sources. <strong>Data import &amp;
          insights</strong>: patterns are computed by code from your rows; the model only
          phrases them, and any wording that invents a number is discarded.
          <strong> Agents</strong>: run on your schedule and always disclose in their output
          that it was AI-generated.
        </p>
      </LegalSection>

      <LegalSection title="4. What data the models see">
        <p>
          Models see what a feature needs: the text you typed, the workspace context the
          feature declares (recent entries, active missions, learned preferences you can
          view and delete in Settings), and — for import analysis — the data you imported.
          Your data is not used to train models: API traffic to Anthropic is not used for
          training under their commercial API terms. Model calls are metered and each one
          is logged to your own usage history.
        </p>
      </LegalSection>

      <LegalSection title="5. AI-generated content is marked">
        <p>
          Content Ionexa generates for an audience beyond you is marked as AI-generated:
          published websites carry a machine-readable marking in their HTML, shared
          presentations state it on the page, research reports and documents carry a notice,
          and every agent email states it was generated by an agent. Outputs can be wrong;
          check anything important before acting on it.
        </p>
      </LegalSection>

      <LegalSection title="6. Human oversight">
        <p>
          Nothing in Ionexa acts autonomously beyond what you configure: generation runs
          when you ask, agents run on schedules you create and can pause, and no AI decision
          (plan steps, classifications, imports) is applied without being visible and
          editable. If you believe an AI output caused a problem, contact us via the contact
          page — every action is logged and traceable.
        </p>
      </LegalSection>
    </LegalLayout>
  );
}
