// The 14 core articles in es, fr, de, it.
//
// FOURTEEN, NOT TWENTY-SEVEN, and the choice is not arbitrary: what the
// product is, everything about money, the four things people come here to
// do, whether the chat remembers you, and how to leave with your data.
// The other thirteen fall back to English, which the loader marks visibly
// rather than pretending it is a translation.
//
// chat-memory was the fourteenth, and it was in the TABLE before it was
// in this file: eight locales carried it in production while the
// generator here knew about thirteen slugs, so the next regeneration
// would have emitted a seed that no longer mentioned it. The row would
// have survived — the seed has no DELETE — but the repo could not
// reproduce the database, which is the same thing as not having it.
//
// Triggers are what a speaker of THAT language actually types. Not a
// translation of the English list — a Spanish user types "cancelar
// suscripción", not "cancel subscription".
export const CORE_SLUGS = [
  "what-is-ionexa", "pricing-overview", "what-are-credits", "credits-ran-out",
  "change-plan", "cancel", "create-website", "create-agent", "create-mission",
  "upload-files", "connect-gmail", "data-privacy", "delete-account",
  // Last in the list, not last in importance: "does it remember me" is
  // the question people ask about a chat before they trust it with
  // anything. Appended rather than inserted so the diff that added it
  // stays readable.
  "chat-memory",
];

export const CORE_1 = {
  es: {
    "what-is-ionexa": { title:"¿Qué es Ionexa?", body:"Un espacio de trabajo donde la IA hace el trabajo en vez de solo aconsejarle: crea su web, ejecuta agentes con una periodicidad fija, divide sus objetivos en pasos, lee sus archivos y responde sobre ellos, y guarda todo lo que registra en un único sitio donde se puede buscar.", triggers:["qué es ionexa","qué es esto","para qué sirve","qué hace","cómo funciona"] },
    "pricing-overview": { title:"¿Cuánto cuesta Ionexa?", body:"Hay un plan gratuito para probarlo y planes de pago según crecen sus necesidades. Los precios actuales y lo que incluye cada uno están siempre en la página /pricing: no se escriben aquí porque cambian y una cifra obsoleta es peor que ninguna.", triggers:["cuánto cuesta","precio","precios","planes","suscripción"] },
    "what-are-credits": { title:"¿Qué son los créditos?", body:"Los créditos son la moneda con la que se pagan las acciones de IA: un mensaje de chat, generar una web, la ejecución de un agente. Cada plan incluye una asignación mensual que se renueva, y puede comprar paquetes extra si se le acaban antes. Cuánto incluye cada plan está en /pricing.", triggers:["qué son los créditos","créditos","cómo funcionan los créditos","unidades"] },
    "credits-ran-out": { title:"Me he quedado sin créditos, ¿y ahora?", body:"Dos opciones: esperar a la renovación mensual, o comprar un paquete de créditos, que se añade al momento y no caduca a fin de mes. Ambas están en Ajustes > Facturación.", triggers:["sin créditos","se me acabaron los créditos","comprar créditos","más créditos"] },
    "change-plan": { title:"¿Cómo cambio de plan?", body:"Ajustes > Facturación. Elija el plan que quiera y el cambio se aplica de inmediato. En una mejora paga solo la diferencia del resto del periodo; en una bajada mantiene el plan actual hasta que termine el periodo ya pagado.", triggers:["cambiar de plan","mejorar plan","bajar de plan","cambiar suscripción"] },
    "cancel": { title:"¿Cómo cancelo mi suscripción?", body:"Ajustes > Facturación > Cancelar suscripción. No pierde el acceso al instante: su plan sigue hasta el final del periodo ya pagado y luego la cuenta pasa al plan gratuito. Sus datos se quedan; cancelar no borra nada.", triggers:["cancelar","cancelar suscripción","darme de baja","anular suscripción"] },
    "create-website": { title:"¿Cómo hago una web?", body:"Abra Website Builder en el menú lateral, escriba con palabras normales qué quiere —a qué se dedica su negocio, a quién se dirige, qué estilo le gusta— y pulse crear. También puede subir imágenes de referencia, un logotipo o fotos de producto, para que siga su estilo. Cuando esté lista la publica en su propia dirección con un clic.", triggers:["hacer una web","crear web","página web","quiero un sitio","website builder"] },
    "create-agent": { title:"¿Cómo creo un agente?", body:"En el menú Agentes, describa en una frase qué quiere que se haga y cada cuánto: por ejemplo «cada mañana envíame un resumen de las noticias de mi sector». Ionexa construye el agente solo, lo ejecuta a su hora y le envía el resultado. Puede pausarlo o cambiarlo cuando quiera.", triggers:["crear agente","hacer un agente","agentes","automatizar","automatización"] },
    "create-mission": { title:"¿Cómo creo una misión?", body:"En Mission Control escribe un objetivo como se lo diría a una persona: «quiero más clientes para la primavera». Ionexa lo divide en pasos concretos, y luego puede trabajarlos usted o encargar alguno a un agente.", triggers:["crear misión","mission control","objetivo","objetivos","misiones"] },
    "upload-files": { title:"¿Puedo subir archivos?", body:"Sí: PDF, Word, Excel, CSV, texto y Markdown. Los sube en Archivos, Ionexa lee su contenido y después puede hacer preguntas sobre ellos. Sus archivos son privados: nadie más tiene acceso y cada descarga usa un enlace temporal.", triggers:["subir archivo","subir","pdf","archivos","documentos"] },
    "connect-gmail": { title:"¿Cómo conecto Gmail o Google Drive?", body:"Ajustes > Conexiones. Elija el servicio y apruebe el acceso en la ventana de Google. Ve exactamente qué va a leer antes de aprobarlo, y puede desconectarlo cuando quiera: las claves de acceso se borran de inmediato.", triggers:["gmail","google drive","conectar","conexión","slack"] },
    "data-privacy": { title:"¿Qué hacen con mis datos?", body:"Sus datos son suyos. No los vendemos, no los usamos para entrenar modelos, y cada cuenta ve solo los suyos: eso se aplica en la base de datos, no solo en la aplicación. Puede descargarlos o borrarlos cuando quiera.", triggers:["mis datos","privacidad","seguridad","venden mis datos","entrenar modelos"] },
    "delete-account": { title:"¿Cómo borro mi cuenta?", body:"Ajustes > Cuenta > Eliminar cuenta. Se le pedirá confirmación y después se borra todo: conversaciones, archivos, webs, agentes, historial. No tiene vuelta atrás. Si quiere una copia antes, descargue sus datos desde la misma página.", triggers:["borrar cuenta","eliminar cuenta","cerrar cuenta","darme de baja del todo"] },
    "chat-memory": { title:"¿El chat recuerda conversaciones anteriores?", body:"Dentro de una misma conversación siempre recuerda los mensajes anteriores. Entre conversaciones distintas guarda solo lo que sigue siendo útil — su nombre, a qué se dedica, sus preferencias — y eso está en los planes de pago. Puede ver todo lo que ha guardado, y borrarlo, en Ajustes > Memoria.", triggers:["recuerda","memoria","conversaciones anteriores","se olvida","no recuerda","historial del chat"] },
  },
  fr: {
    "what-is-ionexa": { title:"Qu'est-ce qu'Ionexa ?", body:"Un espace de travail où l'IA fait le travail au lieu de seulement conseiller : elle crée votre site, exécute des agents selon un calendrier, découpe vos objectifs en étapes, lit vos fichiers et répond à vos questions dessus, et conserve tout ce que vous consignez en un seul endroit consultable.", triggers:["qu'est-ce qu'ionexa","c'est quoi","à quoi ça sert","que fait-il","comment ça marche"] },
    "pricing-overview": { title:"Combien coûte Ionexa ?", body:"Il y a une formule gratuite pour essayer, et des formules payantes à mesure que vos besoins grandissent. Les tarifs actuels et ce que chacune comprend sont toujours sur la page /pricing : ils ne sont pas écrits ici parce qu'ils changent, et un chiffre périmé vaut moins que pas de chiffre.", triggers:["combien ça coûte","prix","tarif","tarifs","formules","abonnement"] },
    "what-are-credits": { title:"Que sont les crédits ?", body:"Les crédits sont la monnaie avec laquelle vous payez les actions d'IA : un message de chat, la génération d'un site, l'exécution d'un agent. Chaque formule comprend une allocation mensuelle qui se renouvelle, et vous pouvez acheter des packs si elle s'épuise plus tôt. Ce que comprend chaque formule est sur /pricing.", triggers:["que sont les crédits","crédits","comment marchent les crédits","unités"] },
    "credits-ran-out": { title:"Je n'ai plus de crédits, que faire ?", body:"Deux possibilités : attendre le renouvellement mensuel, ou acheter un pack de crédits, ajouté immédiatement et qui n'expire pas en fin de mois. Les deux se font dans Paramètres > Facturation.", triggers:["plus de crédits","crédits épuisés","acheter des crédits","recharger"] },
    "change-plan": { title:"Comment changer de formule ?", body:"Paramètres > Facturation. Choisissez la formule voulue et le changement prend effet immédiatement. En montée de gamme vous ne payez que la différence pour le reste de la période ; en descente vous gardez la formule actuelle jusqu'à la fin de la période déjà payée.", triggers:["changer de formule","changer d'offre","passer au supérieur","rétrograder"] },
    "cancel": { title:"Comment résilier mon abonnement ?", body:"Paramètres > Facturation > Résilier l'abonnement. Vous ne perdez pas l'accès tout de suite : votre formule court jusqu'à la fin de la période déjà payée, puis le compte passe à la formule gratuite. Vos données restent — résilier ne supprime rien.", triggers:["résilier","annuler l'abonnement","me désabonner","arrêter l'abonnement"] },
    "create-website": { title:"Comment créer un site ?", body:"Ouvrez Website Builder dans le menu latéral, écrivez en langage courant ce que vous voulez — ce que fait votre activité, à qui elle s'adresse, quel style vous plaît — et lancez la création. Vous pouvez aussi téléverser des images de référence, un logo ou des photos de produits, pour qu'il suive votre identité. Une fois prêt, vous le publiez à sa propre adresse en un clic.", triggers:["créer un site","faire un site","site web","je veux un site","website builder"] },
    "create-agent": { title:"Comment créer un agent ?", body:"Dans le menu Agents, décrivez en une phrase ce que vous voulez faire faire et à quelle fréquence — par exemple « chaque matin, envoie-moi un résumé de l'actualité de mon secteur ». Ionexa construit l'agent lui-même, l'exécute à l'heure dite et vous envoie le résultat. Vous pouvez le mettre en pause ou le modifier quand vous voulez.", triggers:["créer un agent","faire un agent","agents","automatiser","automatisation"] },
    "create-mission": { title:"Comment créer une mission ?", body:"Dans Mission Control, vous écrivez un objectif comme vous le diriez à quelqu'un : « je veux plus de clients d'ici le printemps ». Ionexa le découpe en étapes concrètes, et vous pouvez ensuite les traiter vous-même ou en confier certaines à un agent.", triggers:["créer une mission","mission control","objectif","objectifs","missions"] },
    "upload-files": { title:"Puis-je téléverser des fichiers ?", body:"Oui : PDF, Word, Excel, CSV, texte et Markdown. Vous les déposez dans Fichiers, Ionexa lit leur contenu, puis vous pouvez poser des questions dessus. Vos fichiers sont privés : personne d'autre n'y a accès et chaque téléchargement passe par un lien temporaire.", triggers:["téléverser","importer un fichier","pdf","fichiers","documents"] },
    "connect-gmail": { title:"Comment connecter Gmail ou Google Drive ?", body:"Paramètres > Connexions. Choisissez le service et approuvez l'accès dans la fenêtre de Google. Vous voyez exactement ce qui sera lu avant d'approuver, et vous pouvez déconnecter quand vous voulez — les clés d'accès sont alors supprimées immédiatement.", triggers:["gmail","google drive","connecter","connexion","slack"] },
    "data-privacy": { title:"Que faites-vous de mes données ?", body:"Vos données sont à vous. Nous ne les vendons pas, nous ne nous en servons pas pour entraîner des modèles, et chaque compte ne voit que les siennes — c'est imposé dans la base de données, pas seulement dans l'application. Vous pouvez les télécharger ou les supprimer quand vous voulez.", triggers:["mes données","confidentialité","sécurité","vous vendez mes données","entraîner des modèles"] },
    "delete-account": { title:"Comment supprimer mon compte ?", body:"Paramètres > Compte > Supprimer le compte. Une confirmation vous est demandée, puis tout est supprimé : conversations, fichiers, sites, agents, historique. C'est irréversible. Si vous voulez une copie avant, téléchargez vos données depuis la même page.", triggers:["supprimer mon compte","effacer mon compte","fermer mon compte","supprimer le compte"] },
    "chat-memory": { title:"Le chat se souvient-il des conversations précédentes ?", body:"À l'intérieur d'une même conversation, il se souvient toujours des messages précédents. D'une conversation à l'autre, il ne garde que ce qui reste durablement utile — votre nom, votre métier, vos préférences — et cela existe sur les formules payantes. Vous pouvez voir tout ce qu'il a gardé, et le supprimer, dans Paramètres > Mémoire.", triggers:["se souvient","mémoire","conversations précédentes","il oublie","il ne se souvient pas","historique du chat"] },
  },
  de: {
    "what-is-ionexa": { title:"Was ist Ionexa?", body:"Ein Arbeitsbereich, in dem die KI die Arbeit macht statt nur zu beraten: sie baut deine Website, lässt Agents nach Zeitplan laufen, zerlegt deine Ziele in Schritte, liest deine Dateien und beantwortet Fragen dazu, und hält alles Erfasste an einem durchsuchbaren Ort.", triggers:["was ist ionexa","was ist das","wofür ist das","was macht das","wie funktioniert das"] },
    "pricing-overview": { title:"Was kostet Ionexa?", body:"Es gibt einen kostenlosen Tarif zum Ausprobieren und bezahlte Tarife, wenn die Anforderungen wachsen. Die aktuellen Preise und was jeder Tarif enthält stehen immer auf /pricing — hier nicht, weil sie sich ändern und eine veraltete Zahl schlechter ist als keine.", triggers:["was kostet","preis","preise","tarife","abo","abonnement"] },
    "what-are-credits": { title:"Was sind Credits?", body:"Credits sind die Währung, mit der du KI-Aktionen bezahlst: eine Chat-Nachricht, das Erzeugen einer Website, ein Agent-Lauf. Jeder Tarif enthält ein monatliches Kontingent, das sich erneuert, und du kannst Pakete nachkaufen, wenn es früher aufgebraucht ist. Wie viel jeder Tarif enthält, steht auf /pricing.", triggers:["was sind credits","credits","wie funktionieren credits","einheiten"] },
    "credits-ran-out": { title:"Meine Credits sind aufgebraucht — was jetzt?", body:"Zwei Möglichkeiten: auf die monatliche Erneuerung warten oder ein Credit-Paket kaufen, das sofort gutgeschrieben wird und zum Monatsende nicht verfällt. Beides in Einstellungen > Abrechnung.", triggers:["keine credits mehr","credits aufgebraucht","credits kaufen","mehr credits"] },
    "change-plan": { title:"Wie wechsle ich den Tarif?", body:"Einstellungen > Abrechnung. Wähl den gewünschten Tarif, die Änderung gilt sofort. Beim Upgrade zahlst du nur die Differenz für den Rest der Periode; beim Downgrade behältst du den aktuellen Tarif bis zum Ende der bereits bezahlten Periode.", triggers:["tarif wechseln","upgrade","downgrade","abo ändern"] },
    "cancel": { title:"Wie kündige ich mein Abo?", body:"Einstellungen > Abrechnung > Abo kündigen. Du verlierst den Zugang nicht sofort: dein Tarif läuft bis zum Ende der bereits bezahlten Periode, danach fällt das Konto auf den kostenlosen Tarif. Deine Daten bleiben — Kündigen löscht nichts.", triggers:["kündigen","abo kündigen","abbestellen","abo beenden"] },
    "create-website": { title:"Wie baue ich eine Website?", body:"Öffne Website Builder in der Seitenleiste, schreib in normalen Worten, was du willst — was dein Geschäft macht, für wen es ist, welcher Stil dir gefällt — und starte die Erzeugung. Du kannst auch Referenzbilder hochladen, ein Logo oder Produktfotos, damit sie deinem Look folgt. Wenn sie fertig ist, veröffentlichst du sie mit einem Klick unter eigener Adresse.", triggers:["website bauen","website erstellen","homepage","ich will eine seite","website builder"] },
    "create-agent": { title:"Wie erstelle ich einen Agent?", body:"Im Menü Agents beschreibst du in einem Satz, was getan werden soll und wie oft — zum Beispiel \"schick mir jeden Morgen eine Zusammenfassung der Branchennews\". Ionexa baut den Agent selbst, lässt ihn pünktlich laufen und schickt dir das Ergebnis. Du kannst ihn jederzeit pausieren oder ändern.", triggers:["agent erstellen","agent bauen","agents","automatisieren","automatisierung"] },
    "create-mission": { title:"Wie erstelle ich eine Mission?", body:"In Mission Control schreibst du ein Ziel so, wie du es einem Menschen sagen würdest: \"ich will bis zum Frühjahr mehr Kunden\". Ionexa zerlegt es in konkrete Schritte, und du kannst sie dann selbst abarbeiten oder einzelne an einen Agent übergeben.", triggers:["mission erstellen","mission control","ziel","ziele","missionen"] },
    "upload-files": { title:"Kann ich Dateien hochladen?", body:"Ja — PDF, Word, Excel, CSV, Text und Markdown. Du lädst sie unter Dateien hoch, Ionexa liest ihren Inhalt, und danach kannst du Fragen dazu stellen. Deine Dateien sind privat: niemand sonst hat Zugriff, und jeder Download läuft über einen temporären Link.", triggers:["datei hochladen","hochladen","pdf","dateien","dokumente"] },
    "connect-gmail": { title:"Wie verbinde ich Gmail oder Google Drive?", body:"Einstellungen > Verbindungen. Wähl den Dienst und bestätige den Zugriff in Googles eigenem Fenster. Du siehst vor der Bestätigung genau, was gelesen wird, und kannst jederzeit trennen — die Zugriffsschlüssel werden dann sofort gelöscht.", triggers:["gmail","google drive","verbinden","integration","slack"] },
    "data-privacy": { title:"Was macht ihr mit meinen Daten?", body:"Deine Daten gehören dir. Wir verkaufen sie nicht, wir trainieren keine Modelle damit, und jedes Konto sieht nur die eigenen — das wird in der Datenbank erzwungen, nicht bloß in der Anwendung. Du kannst sie jederzeit herunterladen oder löschen.", triggers:["meine daten","datenschutz","sicherheit","verkauft ihr meine daten","modelle trainieren"] },
    "delete-account": { title:"Wie lösche ich mein Konto?", body:"Einstellungen > Konto > Konto löschen. Du wirst um Bestätigung gebeten, danach ist alles weg: Unterhaltungen, Dateien, Websites, Agents, Verlauf. Das lässt sich nicht rückgängig machen. Wenn du vorher eine Kopie willst, lad deine Daten auf derselben Seite herunter.", triggers:["konto löschen","account löschen","konto schließen","profil löschen"] },
    "chat-memory": { title:"Merkt sich der Chat frühere Unterhaltungen?", body:"Innerhalb einer Unterhaltung merkt er sich die früheren Nachrichten immer. Zwischen verschiedenen Unterhaltungen behält er nur dauerhaft Nützliches — deinen Namen, was du machst, deine Vorlieben — und das gibt es in den bezahlten Tarifen. Was er behalten hat, kannst du unter Einstellungen > Erinnerung ansehen und löschen.", triggers:["merkt sich","erinnert sich","gedächtnis","frühere unterhaltungen","vergisst","chatverlauf"] },
  },
  it: {
    "what-is-ionexa": { title:"Che cos'è Ionexa?", body:"Uno spazio di lavoro dove l'AI fa il lavoro invece di limitarsi a consigliare: crea il tuo sito, esegue agent secondo una pianificazione, divide i tuoi obiettivi in passi, legge i tuoi file e risponde su di essi, e tiene tutto ciò che registri in un unico posto ricercabile.", triggers:["cos'è ionexa","che cos'è","a cosa serve","cosa fa","come funziona"] },
    "pricing-overview": { title:"Quanto costa Ionexa?", body:"C'è un piano gratuito per provarlo e piani a pagamento man mano che le esigenze crescono. I prezzi attuali e cosa include ciascuno sono sempre sulla pagina /pricing: non li scriviamo qui perché cambiano e un numero vecchio è peggio di nessun numero.", triggers:["quanto costa","prezzo","prezzi","piani","abbonamento"] },
    "what-are-credits": { title:"Cosa sono i credits?", body:"I credits sono la moneta con cui paghi le azioni AI: un messaggio in chat, la generazione di un sito, l'esecuzione di un agent. Ogni piano include una dotazione mensile che si rinnova, e puoi comprare pacchetti extra se finisce prima. Quanto include ogni piano è su /pricing.", triggers:["cosa sono i credits","credits","come funzionano i credits","unità"] },
    "credits-ran-out": { title:"Ho finito i credits, e adesso?", body:"Due possibilità: aspettare il rinnovo mensile, oppure comprare un pacchetto di credits, che viene aggiunto subito e non scade a fine mese. Entrambe si trovano in Impostazioni > Fatturazione.", triggers:["finiti i credits","senza credits","comprare credits","altri credits"] },
    "change-plan": { title:"Come cambio piano?", body:"Impostazioni > Fatturazione. Scegli il piano che vuoi e il cambio ha effetto subito. In caso di passaggio superiore paghi solo la differenza per il resto del periodo; scendendo mantieni il piano attuale fino alla fine del periodo già pagato.", triggers:["cambiare piano","passare a un piano superiore","downgrade","cambiare abbonamento"] },
    "cancel": { title:"Come annullo l'abbonamento?", body:"Impostazioni > Fatturazione > Annulla abbonamento. Non perdi subito l'accesso: il piano prosegue fino alla fine del periodo già pagato e poi l'account passa al piano gratuito. I tuoi dati restano — annullare non cancella niente.", triggers:["annullare","disdire l'abbonamento","cancellare abbonamento","disiscrivermi"] },
    "create-website": { title:"Come faccio un sito?", body:"Apri Website Builder dal menù laterale, scrivi a parole tue cosa vuoi — cosa fa la tua attività, a chi si rivolge, che stile ti piace — e avvia la creazione. Puoi anche caricare immagini di riferimento, un logo o foto di prodotto, così segue il tuo stile. Quando è pronto lo pubblichi a un indirizzo suo con un clic.", triggers:["fare un sito","creare sito","sito web","voglio un sito","website builder"] },
    "create-agent": { title:"Come creo un agent?", body:"Nel menù Agent, descrivi in una frase cosa vuoi che venga fatto e ogni quanto — per esempio «ogni mattina mandami un riassunto delle notizie del mio settore». Ionexa costruisce l'agent da sé, lo esegue in orario e ti manda il risultato. Puoi metterlo in pausa o modificarlo quando vuoi.", triggers:["creare agent","fare un agent","agent","automatizzare","automazione"] },
    "create-mission": { title:"Come creo una mission?", body:"In Mission Control scrivi un obiettivo come lo diresti a una persona: «voglio più clienti entro la primavera». Ionexa lo divide in passi concreti, e poi puoi lavorarli tu o affidarne qualcuno a un agent.", triggers:["creare mission","mission control","obiettivo","obiettivi","mission"] },
    "upload-files": { title:"Posso caricare file?", body:"Sì — PDF, Word, Excel, CSV, testo e Markdown. Li carichi in File, Ionexa ne legge il contenuto e poi puoi fare domande su di essi. I tuoi file sono privati: nessun altro vi ha accesso e ogni download usa un link temporaneo.", triggers:["caricare file","caricare","pdf","file","documenti"] },
    "connect-gmail": { title:"Come collego Gmail o Google Drive?", body:"Impostazioni > Connessioni. Scegli il servizio e approva l'accesso nella finestra di Google. Vedi esattamente cosa verrà letto prima di approvare, e puoi scollegare quando vuoi — le chiavi di accesso vengono cancellate subito.", triggers:["gmail","google drive","collegare","connessione","slack"] },
    "data-privacy": { title:"Cosa fate con i miei dati?", body:"I tuoi dati sono tuoi. Non li vendiamo, non li usiamo per addestrare modelli, e ogni account vede solo i propri — è imposto nel database, non solo nell'applicazione. Puoi scaricarli o cancellarli quando vuoi.", triggers:["i miei dati","privacy","sicurezza","vendete i miei dati","addestrare modelli"] },
    "delete-account": { title:"Come cancello il mio account?", body:"Impostazioni > Account > Elimina account. Ti verrà chiesta conferma, poi viene cancellato tutto: conversazioni, file, siti, agent, cronologia. Non è reversibile. Se prima vuoi una copia, scarica i tuoi dati dalla stessa pagina.", triggers:["cancellare account","eliminare account","chiudere l'account","cancellare profilo"] },
    "chat-memory": { title:"La chat ricorda le conversazioni precedenti?", body:"All'interno della stessa conversazione ricorda sempre i messaggi precedenti. Tra conversazioni diverse conserva solo ciò che resta utile a lungo — il suo nome, di cosa si occupa, le sue preferenze — e questo è disponibile nei piani a pagamento. Può vedere tutto ciò che ha conservato, ed eliminarlo, in Impostazioni > Memoria.", triggers:["ricorda","memoria","conversazioni precedenti","dimentica","non ricorda","cronologia della chat"] },
  },
};
