-- The Help Centre, in ten languages.
--
-- GENERATED by scripts/generate-help-seed.mjs from content/help/.
-- Do not edit this file by hand: scripts/tests/help-articles.test.mjs
-- regenerates it and compares, so a hand edit fails the build. Edit the
-- JSON and re-run the generator.
--
-- IDEMPOTENT. Every statement is guarded. No DROP TABLE, no TRUNCATE, no
-- unqualified DELETE, no DROP CONSTRAINT, no DROP POLICY.
--
-- ============================================================================
-- WHAT WAS WRONG
-- ============================================================================
-- Twenty-seven help articles lived as Greek string literals in
-- src/lib/support/knowledge-base.ts and were served to all ten locales. A
-- Japanese reader opening /help got Greek. The same array fed the support
-- chat's canned answers, so the same reader could also be handed a Greek
-- paragraph in place of an answer.
--
-- ============================================================================
-- THE SHAPE
-- ============================================================================
-- One row per (slug, locale). English is the BASE: every article exists in
-- English, and a reader whose language is missing an article is shown the
-- English one with a visible marker saying so.
--
-- The fallback is structural, not a filter someone can forget: the loader
-- selects locale IN (requested, 'en') and never widens that set, so Greek
-- cannot reach a non-Greek reader by any code path. Greek is one more
-- translation here, with no privileges.
--
-- ROWS: 158 total across 10 locales
--   en=27  el=27  es=13  fr=13  de=13  it=13  pt=13  zh=13  ja=13  ar=13
--
-- ============================================================================
-- ONE COLUMN BEYOND THE AGREED SHAPE, AND WHY
-- ============================================================================
-- `triggers text[]` is not in the column list this table was specified
-- with. It is here because the table also feeds the support chat's canned
-- answers, and matching "how do i cancel" to an article needs the phrases
-- people type — per language, since a French reader does not type Greek.
-- Keeping those in TypeScript would put half the content back in the code
-- this migration exists to empty. Everything else matches the agreed shape.
--
-- `href` is deliberately NOT here. A route is code, not content: it is the
-- same in every language, storing it once per row invites 158 chances to
-- drift, and scripts/tests/help-links.test.mjs can only prove a route
-- exists if it can see it in the repo. It lives in
-- src/lib/support/help-links.ts.

-- 1. The table -------------------------------------------------------------
create table if not exists public.help_articles (
  id uuid primary key default gen_random_uuid(),
  slug text not null,
  locale text not null,
  title text not null,
  body text not null,
  category text not null,
  "order" integer not null default 0,
  published boolean not null default true,
  -- Phrases a reader types, in THIS locale. See the note above.
  triggers text[] not null default '{}'::text[],
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

-- Columns added separately as well, so the file repairs a table that was
-- created by an earlier version of it rather than failing on the insert.
alter table public.help_articles add column if not exists triggers text[] not null default '{}'::text[];
alter table public.help_articles add column if not exists published boolean not null default true;
alter table public.help_articles add column if not exists "order" integer not null default 0;
alter table public.help_articles add column if not exists created_at timestamptz not null default now();
alter table public.help_articles add column if not exists updated_at timestamptz not null default now();

-- 2. The identity of a translation ------------------------------------------
-- (slug, locale) is what makes the French "cancel" a translation of the
-- English "cancel" rather than a second, unrelated article. It is also what
-- the seed's ON CONFLICT targets, so without it the seed is not idempotent.
create unique index if not exists help_articles_slug_locale_uidx
  on public.help_articles (slug, locale);

-- The read path: everything published in one language, in display order.
create index if not exists help_articles_locale_published_idx
  on public.help_articles (locale, published, category, "order");

-- 3. Constraints -------------------------------------------------------------
-- The database refuses a locale or a category the application does not
-- know. A TypeScript union stops a developer; this stops a SQL console, a
-- backfill, and a future admin screen.
do $locale_check$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'help_articles_locale_check'
       and conrelid = 'public.help_articles'::regclass
  ) then
    alter table public.help_articles
      add constraint help_articles_locale_check
      check (locale in ('en', 'el', 'es', 'fr', 'de', 'it', 'pt', 'zh', 'ja', 'ar'));
  end if;
end
$locale_check$;

do $category_check$
begin
  if not exists (
    select 1 from pg_constraint
     where conname = 'help_articles_category_check'
       and conrelid = 'public.help_articles'::regclass
  ) then
    alter table public.help_articles
      add constraint help_articles_category_check
      check (category in ('getting-started', 'billing', 'credits', 'websites', 'agents', 'missions', 'chat', 'files', 'integrations', 'account', 'privacy'));
  end if;
end
$category_check$;

-- 4. updated_at ---------------------------------------------------------------
create or replace function public.help_articles_touch_updated_at()
returns trigger
language plpgsql
set search_path = public
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;

do $touch_trigger$
begin
  if not exists (
    select 1 from pg_trigger
     where tgname = 'help_articles_touch_updated_at_trg'
       and tgrelid = 'public.help_articles'::regclass
  ) then
    create trigger help_articles_touch_updated_at_trg
      before update on public.help_articles
      for each row execute function public.help_articles_touch_updated_at();
  end if;
end
$touch_trigger$;

-- 5. RLS ----------------------------------------------------------------------
-- Public read of PUBLISHED rows: half of these answers — what does it cost,
-- what are credits, is my data safe — are asked before anyone has an
-- account, and an answer you must sign up to read is not an answer.
--
-- Writes: there is no insert, update or delete policy, on purpose. With RLS
-- enabled and no write policy, every anon and authenticated write is
-- refused by the database; the service role bypasses RLS and is the only
-- way content changes. That is "service-role write" expressed as the
-- absence of a hole rather than as a rule someone has to get right.
alter table public.help_articles enable row level security;

do $read_policy$
begin
  if not exists (
    select 1 from pg_policies
     where schemaname = 'public'
       and tablename = 'help_articles'
       and policyname = 'help_articles_public_read_published'
  ) then
    create policy "help_articles_public_read_published"
      on public.help_articles
      for select
      using (published = true);
  end if;
end
$read_policy$;

grant select on public.help_articles to anon, authenticated;

-- 6. The content ---------------------------------------------------------------
-- ON CONFLICT DO UPDATE: this migration is the source of the shipped copy,
-- so re-running it restores that copy. To change an article, edit
-- content/help/<locale>.json and regenerate — do not edit rows by hand, or
-- the next run of this file will quietly undo you.
--
-- created_at is NOT in the update list: a re-run must not rewrite when a
-- row first appeared.
insert into public.help_articles (slug, locale, title, body, category, "order", triggers, published)
values
  ('what-is-ionexa', 'en', 'What is Ionexa?', 'A workspace where you say what you want and it happens: it builds websites, runs agents that work on their own schedule, breaks goals down into steps, and reads your files so it can answer questions about them.

Instead of ten separate tools that do not talk to each other, one that knows about all of it.', 'getting-started', 10, array['what is ionexa', 'what does ionexa do', 'what is this', 'what do you offer', 'about ionexa', 'explain ionexa']::text[], true),
  ('what-is-ionexa', 'el', 'Τι είναι το Ionexa;', 'Ένας χώρος εργασίας όπου λες τι θέλεις και γίνεται: φτιάχνει websites, τρέχει agents που δουλεύουν μόνοι τους σε πρόγραμμα, σπάει στόχους σε βήματα, διαβάζει τα αρχεία σου και απαντά πάνω σε αυτά.

Αντί για δέκα ξεχωριστά εργαλεία που δεν μιλάνε μεταξύ τους, ένα που τα ξέρει όλα.', 'getting-started', 10, array['τι ειναι το ionexa', 'τι κανει το ionexa', 'τι ειναι αυτο', 'τι προσφερετε', 'what is ionexa', 'σχετικα']::text[], true),
  ('what-is-ionexa', 'es', '¿Qué es Ionexa?', 'Un espacio de trabajo donde dices lo que quieres y se hace: crea sitios web, pone a funcionar agentes que trabajan solos y a su hora, divide tus objetivos en pasos y lee tus archivos para poder responderte sobre ellos.

En vez de diez herramientas sueltas que no se hablan entre sí, una sola que lo sabe todo.', 'getting-started', 10, array['que es ionexa', 'que hace ionexa', 'que es esto', 'para que sirve', 'de que va esto', 'que ofreceis', 'explicame ionexa', 'informacion sobre ionexa']::text[], true),
  ('what-is-ionexa', 'fr', 'Qu''est-ce qu''Ionexa ?', 'Un espace de travail où il suffit de dire ce que vous voulez pour que ce soit fait : il crée des sites web, fait tourner des agents qui travaillent seuls selon leur planning, découpe vos objectifs en étapes et lit vos fichiers pour répondre à vos questions dessus.

Au lieu de dix outils séparés qui ne se parlent pas, un seul qui est au courant de tout.', 'getting-started', 10, array['c est quoi ionexa', 'qu est ce qu ionexa', 'ionexa c est quoi', 'a quoi sert ionexa', 'que fait ionexa', 'a quoi ca sert', 'qu est ce que vous proposez', 'c est quoi ce truc']::text[], true),
  ('what-is-ionexa', 'de', 'Was ist Ionexa?', 'Ein Arbeitsbereich, in dem du sagst, was du willst, und es passiert: Er baut Websites, lässt Agenten nach eigenem Zeitplan für dich laufen, zerlegt Ziele in einzelne Schritte und liest deine Dateien, damit er dir Fragen dazu beantworten kann.

Statt zehn einzelner Tools, die nicht miteinander reden, eines, das von allem weiß.', 'getting-started', 10, array['was ist ionexa', 'was macht ionexa', 'was ist das hier', 'was kann das', 'wofur ist das', 'worum geht es hier', 'ionexa erklaren', 'was bringt mir das']::text[], true),
  ('what-is-ionexa', 'it', 'Che cos''è Ionexa?', 'Un''area di lavoro dove dici che cosa ti serve e viene fatto: genera siti web, fa girare agenti che lavorano da soli secondo la loro pianificazione, divide i tuoi obiettivi in passaggi e legge i tuoi file per poi risponderti su quello che contengono.

Invece di dieci strumenti separati che non si parlano tra loro, uno solo che sa tutto.', 'getting-started', 10, array['cos e ionexa', 'che cos e ionexa', 'cosa fa ionexa', 'a cosa serve ionexa', 'che cos e questo', 'come funziona ionexa', 'cosa offrite', 'informazioni su ionexa']::text[], true),
  ('what-is-ionexa', 'pt', 'O que é o Ionexa?', 'Um espaço de trabalho onde dizes o que queres e acontece: cria sites, põe agentes a trabalhar sozinhos com horário próprio, divide objetivos em passos e lê os teus ficheiros para responder sobre eles.

Em vez de dez ferramentas separadas que não falam entre si, uma que sabe de tudo.', 'getting-started', 10, array['o que e o ionexa', 'o que faz o ionexa', 'o que e isto', 'para que serve', 'sobre o ionexa', 'como funciona isto']::text[], true),
  ('what-is-ionexa', 'zh', 'Ionexa 是什么？', '一个说出需求就能完成的工作空间：它能生成网站、按自己的时间表运行智能体、把目标拆成具体步骤，还能读你的文件并据此回答问题。

与其用十个互不相通的工具，不如用一个全都知道的。', 'getting-started', 10, array['ionexa是什么', '这是什么', '有什么用', '能做什么', '介绍一下', '怎么用']::text[], true),
  ('what-is-ionexa', 'ja', 'Ionexa とは何ですか？', 'やりたいことを言葉にすると、それが形になるワークスペースです。ウェブサイトを作り、エージェントが自分のスケジュールで動き、目標を具体的な手順に分解し、アップロードしたファイルを読んでその内容に答えます。

互いに連携しない十個のツールを使い分ける代わりに、すべてを把握している一つを使う、という考え方です。', 'getting-started', 10, array['ionexaとは', 'これは何', '何ができる', 'どんなサービス', '使い方', '概要']::text[], true),
  ('what-is-ionexa', 'ar', 'ما هو Ionexa؟', 'مساحة عمل تقول فيها ما تريد فيحدث: تُنشئ المواقع، وتُشغّل وكلاء يعملون وحدهم وفق جدولهم، وتُقسّم الأهداف إلى خطوات، وتقرأ ملفاتك لتجيب عن أسئلتك حولها.

بدل عشر أدوات منفصلة لا يعرف بعضها بعضًا، أداة واحدة تعرف كل شيء.', 'getting-started', 10, array['ما هو ionexa', 'ما هذا', 'ماذا يفعل', 'ما فائدته', 'عن ionexa', 'كيف يعمل']::text[], true),
  ('languages', 'en', 'What languages does it work in?', 'The interface is available in ten languages and you switch it in Settings.

The AI replies in whatever language you write to it, regardless of the interface language — so you can keep the interface in English and still chat in your own language.', 'getting-started', 20, array['language', 'languages', 'change language', 'translation', 'in my language', 'english interface']::text[], true),
  ('languages', 'el', 'Σε ποιες γλώσσες δουλεύει;', 'Το περιβάλλον υπάρχει σε δέκα γλώσσες και το αλλάζεις από τις Ρυθμίσεις.

Το AI απαντά στη γλώσσα που του γράφεις, ανεξάρτητα από τη γλώσσα του περιβάλλοντος — μπορείς δηλαδή να έχεις το περιβάλλον στα αγγλικά και να συνομιλείς στα ελληνικά.', 'getting-started', 20, array['γλωσσα', 'γλωσσες', 'language', 'αγγλικα', 'ελληνικα', 'μεταφραση', 'αλλαγη γλωσσας']::text[], true),
  ('mobile-app', 'en', 'Is there a mobile app?', 'Ionexa installs on your phone straight from the browser — open it and choose "Add to Home Screen".

It behaves like a normal app, with its own icon and notifications, without going through an app store.', 'getting-started', 30, array['mobile app', 'phone app', 'android', 'iphone', 'ios', 'app store', 'install on phone']::text[], true),
  ('mobile-app', 'el', 'Υπάρχει εφαρμογή για κινητό;', 'Το Ionexa εγκαθίσταται στο κινητό σου απευθείας από τον browser — άνοιξέ το και διάλεξε «Προσθήκη στην αρχική οθόνη».

Λειτουργεί σαν κανονική εφαρμογή, με εικονίδιο και ειδοποιήσεις, χωρίς να περάσεις από app store.', 'getting-started', 30, array['εφαρμογη κινητου', 'mobile app', 'android', 'iphone', 'ios', 'κινητο', 'app', 'εφαρμογη']::text[], true),
  ('pricing-overview', 'en', 'How much does Ionexa cost?', 'There is a free plan so you can try it, and paid plans as your needs grow.

Current prices and what each plan includes are always on the pricing page. They are not repeated here on purpose — a stale number is worse than no number.', 'billing', 10, array['how much does it cost', 'price', 'prices', 'cost', 'pricing', 'how much', 'what plans are there', 'which plans', 'plans', 'subscription cost']::text[], true),
  ('pricing-overview', 'el', 'Πόσο κοστίζει το Ionexa;', 'Υπάρχει δωρεάν πλάνο για να δοκιμάσεις, και επί πληρωμή πλάνα καθώς μεγαλώνουν οι ανάγκες σου.

Οι τρέχουσες τιμές και το τι περιλαμβάνει το καθένα είναι πάντα στη σελίδα τιμών. Δεν τις γράφω εδώ επίτηδες — ένα παλιό νούμερο είναι χειρότερο από κανένα.', 'billing', 10, array['ποσο κοστιζει', 'τιμη', 'τιμες', 'κοστος', 'ποσο κανει', 'how much', 'pricing', 'price', 'τι πακετα υπαρχουν', 'ποια πακετα', 'πλανα', 'plans', 'συνδρομη', 'subscription']::text[], true),
  ('pricing-overview', 'es', '¿Cuánto cuesta Ionexa?', 'Hay un plan gratuito para que lo pruebes, y planes de pago según van creciendo tus necesidades.

Los precios de hoy y lo que incluye cada plan están siempre en la página de Precios. No los repito aquí a propósito: un número viejo es peor que ningún número.', 'billing', 10, array['cuanto cuesta', 'precio', 'precios', 'cuanto vale', 'que planes hay', 'planes', 'tarifas', 'suscripcion', 'es gratis']::text[], true),
  ('pricing-overview', 'fr', 'Combien coûte Ionexa ?', 'Il y a un forfait gratuit pour essayer, et des forfaits payants quand vos besoins grandissent.

Les tarifs à jour et ce que contient chaque forfait sont toujours sur la page Tarifs. Ils ne sont pas recopiés ici, et c''est volontaire : un tarif périmé est pire que pas de tarif du tout.', 'billing', 10, array['combien ca coute', 'ca coute combien', 'prix', 'tarifs', 'quels sont les tarifs', 'quels forfaits existent', 'c est payant', 'cout de l abonnement']::text[], true),
  ('pricing-overview', 'de', 'Was kostet Ionexa?', 'Es gibt einen kostenlosen Tarif zum Ausprobieren und bezahlte Tarife, wenn deine Ansprüche wachsen.

Die aktuellen Preise und was in welchem Tarif steckt, stehen immer auf der Seite „Preise“. Hier stehen sie mit Absicht nicht — eine veraltete Zahl ist schlimmer als gar keine.', 'billing', 10, array['was kostet ionexa', 'was kostet das', 'was kostet es', 'preise', 'wie teuer ist das', 'welche tarife gibt es', 'ist das kostenlos', 'kosten', 'abo preis']::text[], true),
  ('pricing-overview', 'it', 'Quanto costa Ionexa?', 'C''è un piano gratuito per provarlo, e piani a pagamento man mano che crescono le tue esigenze.

I prezzi aggiornati e quello che include ogni piano sono sempre sulla pagina Prezzi. Qui non li ripeto di proposito: un numero vecchio è peggio di nessun numero.', 'billing', 10, array['quanto costa', 'quanto costa ionexa', 'prezzi', 'prezzo', 'costi', 'che piani ci sono', 'quali piani', 'quanto costa abbonarsi', 'e gratis']::text[], true),
  ('pricing-overview', 'pt', 'Quanto custa o Ionexa?', 'Há um plano gratuito para experimentares e planos pagos à medida que as tuas necessidades crescem.

Os preços atuais e o que cada plano inclui estão sempre na página Preços. Não os repetimos aqui de propósito — um número desatualizado é pior do que número nenhum.', 'billing', 10, array['quanto custa', 'preco', 'precos', 'custo', 'quanto e', 'que planos existem', 'planos', 'quanto pago', 'mensalidade']::text[], true),
  ('pricing-overview', 'zh', 'Ionexa 怎么收费？', '有免费方案可以先试用，需求变大之后再选付费方案。

当前价格和每个方案包含的内容始终在定价页面上。这里刻意不重复写出来——过时的数字比没有数字更糟。', 'billing', 10, array['多少钱', '价格', '收费', '怎么收费', '有哪些方案', '套餐', '订阅费用', '贵不贵']::text[], true),
  ('pricing-overview', 'ja', 'Ionexa の料金はいくらですか？', 'まずお試しいただける無料プランがあり、必要に応じて有料プランをご用意しています。

現在の価格と各プランの内容は、常に料金ページに掲載しています。ここにあえて書かないのは、古い数字が載っているほうが何も書かれていないより悪いからです。', 'billing', 10, array['いくら', '料金', '価格', '費用', 'プラン', 'どんなプラン', '月額', '値段']::text[], true),
  ('pricing-overview', 'ar', 'كم يكلّف Ionexa؟', 'هناك خطة مجانية للتجربة، وخطط مدفوعة كلما كبرت احتياجاتك.

الأسعار الحالية وما تتضمنه كل خطة موجودة دائمًا في صفحة الأسعار. لا نكررها هنا عن قصد، فالرقم القديم أسوأ من غياب الرقم.', 'billing', 10, array['كم السعر', 'السعر', 'الاسعار', 'التكلفة', 'كم يكلف', 'ما هي الخطط', 'الخطط', 'الاشتراك كم']::text[], true),
  ('change-plan', 'en', 'How do I change my plan?', 'Settings → Billing. Pick the plan you want and the change takes effect straight away.

On an upgrade you pay only the difference for the rest of the current period. On a downgrade you keep your current plan until the period you have already paid for ends.', 'billing', 20, array['how do i change plan', 'change plan', 'upgrade', 'downgrade', 'switch plan', 'change subscription']::text[], true),
  ('change-plan', 'el', 'Πώς αλλάζω πλάνο;', 'Από τις Ρυθμίσεις → Χρέωση. Επιλέγεις το πλάνο που θέλεις και η αλλαγή ισχύει αμέσως.

Σε αναβάθμιση πληρώνεις μόνο τη διαφορά για το υπόλοιπο της περιόδου· σε υποβάθμιση κρατάς το τρέχον πλάνο μέχρι να τελειώσει η περίοδος που έχεις ήδη πληρώσει.', 'billing', 20, array['πως αλλαζω πλανο', 'αλλαγη πλανου', 'αναβαθμιση', 'upgrade', 'downgrade', 'υποβαθμιση', 'change plan', 'αλλαξω συνδρομη']::text[], true),
  ('cancel', 'en', 'How do I cancel my subscription?', 'Settings → Billing → Cancel subscription. It takes one click to reach and one to confirm.

You do not lose access immediately: your plan runs to the end of the period you have already paid for, and only then does the account move to the free plan. Nothing is deleted — your data, files and websites stay exactly where they are.

Changed your mind? The same screen lets you restore the subscription at any point before it ends.', 'billing', 30, array['how do i cancel', 'cancel', 'cancel subscription', 'unsubscribe', 'stop my subscription', 'end subscription', 'quit']::text[], true),
  ('cancel', 'el', 'Πώς ακυρώνω τη συνδρομή μου;', 'Ρυθμίσεις → Χρέωση → Ακύρωση συνδρομής. Ένα κλικ για να τη βρεις, ένα για να την επιβεβαιώσεις.

Δεν χάνεις αμέσως την πρόσβαση: το πλάνο σου συνεχίζει μέχρι το τέλος της περιόδου που έχεις ήδη πληρώσει και μόνο τότε ο λογαριασμός πέφτει στο δωρεάν πλάνο. Δεν διαγράφεται τίποτα — τα δεδομένα, τα αρχεία και τα websites σου μένουν ακριβώς εκεί που είναι.

Άλλαξες γνώμη; Από την ίδια οθόνη μπορείς να επαναφέρεις τη συνδρομή οποτεδήποτε πριν λήξει.', 'billing', 30, array['πως ακυρωνω', 'ακυρωση', 'να ακυρωσω', 'cancel', 'unsubscribe', 'διακοπη συνδρομης', 'σταματησω τη συνδρομη', 'ακυρωση συνδρομης']::text[], true),
  ('cancel', 'es', '¿Cómo cancelo mi suscripción?', 'Configuración → Facturación → Cancelar la suscripción. Un clic para llegar y otro para confirmar.

No pierdes el acceso de golpe: tu plan sigue hasta el final del periodo que ya has pagado y solo entonces la cuenta pasa al plan gratuito. No se borra nada — tus datos, tus archivos y tus sitios web se quedan donde están.

¿Te has arrepentido? Desde esa misma pantalla puedes restaurar la suscripción en cualquier momento antes de que termine.', 'billing', 30, array['como cancelo', 'cancelar', 'cancelar suscripcion', 'darme de baja', 'dar de baja', 'quiero cancelar', 'anular la suscripcion', 'baja']::text[], true),
  ('cancel', 'fr', 'Comment résilier mon abonnement ?', 'Paramètres → Facturation → Résilier l''abonnement. Un clic pour y arriver, un clic pour confirmer.

Vous ne perdez pas l''accès tout de suite : votre forfait continue jusqu''à la fin de la période déjà payée, et c''est seulement là que le compte bascule sur le forfait gratuit. Rien n''est supprimé — vos données, vos fichiers et vos sites web restent exactement où ils sont.

Vous changez d''avis ? Le même écran vous permet de rétablir l''abonnement à tout moment avant la fin.', 'billing', 30, array['comment resilier', 'resilier', 'resilier mon abonnement', 'annuler mon abonnement', 'je veux arreter', 'se desabonner', 'arreter l abonnement', 'mettre fin a l abonnement']::text[], true),
  ('cancel', 'de', 'Wie kündige ich mein Abo?', 'Einstellungen → Abrechnung → Abo kündigen. Ein Klick dorthin, ein Klick zum Bestätigen.

Den Zugang verlierst du nicht sofort: Dein Tarif läuft bis zum Ende des Zeitraums weiter, den du bereits bezahlt hast, und erst dann wechselt das Konto in den kostenlosen Tarif. Gelöscht wird nichts — deine Daten, deine Dateien und deine Websites bleiben genau dort, wo sie sind.

Du hast es dir anders überlegt? Auf demselben Bildschirm kannst du das Abo jederzeit vor Ablauf wieder reaktivieren.', 'billing', 30, array['abo kundigen', 'kundigen', 'wie kundige ich', 'abo beenden', 'kundigung', 'vertrag kundigen', 'abo canceln', 'abo stoppen']::text[], true),
  ('cancel', 'it', 'Come disdico l''abbonamento?', 'Impostazioni → Fatturazione → Disdici l''abbonamento. Un clic per arrivarci, uno per confermare.

Non perdi subito l''accesso: il tuo piano resta attivo fino alla fine del periodo che hai già pagato, e solo allora l''account passa al piano gratuito. Non viene eliminato nulla — i tuoi dati, i tuoi file e i tuoi siti web restano esattamente dove sono.

Hai cambiato idea? Dalla stessa schermata puoi ripristinare l''abbonamento in qualsiasi momento prima della scadenza.', 'billing', 30, array['come disdico', 'disdire abbonamento', 'disdetta', 'annullare abbonamento', 'cancellare abbonamento', 'voglio disdire', 'come faccio a disdire', 'chiudere abbonamento']::text[], true),
  ('cancel', 'pt', 'Como cancelo a minha subscrição?', 'Configurações → Faturação → Cancelar subscrição. Um clique para lá chegar, outro para confirmar.

Não perdes o acesso de imediato: o teu plano continua até ao fim do período que já pagaste e só depois a conta passa para o plano gratuito. Não se apaga nada — os teus dados, ficheiros e sites ficam exatamente onde estão.

Mudaste de ideias? No mesmo ecrã podes repor a subscrição a qualquer momento antes de terminar.', 'billing', 30, array['como cancelo', 'cancelar', 'cancelar subscricao', 'anular subscricao', 'quero cancelar', 'parar a subscricao', 'terminar assinatura']::text[], true),
  ('cancel', 'zh', '怎么取消订阅？', '设置 → 账单 → 取消订阅。一次点击就能找到，再一次确认即可。

你不会立刻失去访问权限：已经付费的周期照常用到结束，之后账户才转为免费方案。什么都不会被删除——你的数据、文件和网站都原样保留。

改主意了？在同一个界面上，在订阅结束前随时都可以恢复。', 'billing', 30, array['怎么取消', '取消订阅', '退订', '不想续费', '停止订阅', '结束订阅']::text[], true),
  ('cancel', 'ja', 'サブスクリプションを解約するには？', '設定 → 請求 → サブスクリプションの解約。たどり着くのに一回、確認に一回のクリックだけです。

すぐに使えなくなることはありません。すでにお支払いいただいた期間の終わりまでプランは続き、そのあとで無料プランに切り替わります。削除されるものは何もありません。データもファイルもウェブサイトもそのまま残ります。

気が変わった場合は、終了前であれば同じ画面からいつでも元に戻せます。', 'billing', 30, array['解約したい', '解約', 'キャンセル', '退会', 'サブスクをやめたい', '課金を止めたい']::text[], true),
  ('cancel', 'ar', 'كيف ألغي اشتراكي؟', 'الإعدادات ← الفوترة ← إلغاء الاشتراك. نقرة واحدة للوصول، وأخرى للتأكيد.

لن تفقد الوصول فورًا: تستمر خطتك حتى نهاية المدة التي دفعتها بالفعل، وعندها فقط ينتقل الحساب إلى الخطة المجانية. ولا يُحذف شيء — بياناتك وملفاتك ومواقعك تبقى كما هي.

غيّرت رأيك؟ من الشاشة نفسها يمكنك استعادة الاشتراك في أي وقت قبل انتهائه.', 'billing', 30, array['كيف الغي', 'الغاء', 'الغاء الاشتراك', 'ايقاف الاشتراك', 'اريد الالغاء', 'انهاء الاشتراك']::text[], true),
  ('invoices', 'en', 'Where do I find my receipts?', 'Settings → Billing → Payment history. Every charge has a PDF receipt you can download from there.

Payments are handled by Stripe and we never store your card details.', 'billing', 40, array['receipt', 'receipts', 'invoice', 'invoices', 'billing history', 'payment history', 'vat receipt']::text[], true),
  ('invoices', 'el', 'Πού βρίσκω τις αποδείξεις μου;', 'Ρυθμίσεις → Χρέωση → Ιστορικό πληρωμών. Κάθε χρέωση έχει απόδειξη σε PDF που κατεβάζεις από εκεί.

Οι πληρωμές γίνονται μέσω Stripe και δεν αποθηκεύουμε ποτέ τα στοιχεία της κάρτας σου.', 'billing', 40, array['αποδειξη', 'αποδειξεις', 'τιμολογιο', 'invoice', 'receipt', 'ιστορικο πληρωμων', 'παραστατικο']::text[], true),
  ('refund', 'en', 'Can I ask for a refund?', 'Yes — tell us what happened and we will look at it. If you were charged by mistake, or something did not work the way it should have, we will put it right.

Message us from Settings → Support and include the charge reference so we can find it quickly.', 'billing', 50, array['refund', 'money back', 'charged by mistake', 'wrong charge', 'double charged', 'get my money back']::text[], true),
  ('refund', 'el', 'Μπορώ να ζητήσω επιστροφή χρημάτων;', 'Ναι — γράψε μας τι έγινε και θα το δούμε. Αν χρεώθηκες κατά λάθος ή κάτι δεν δούλεψε όπως έπρεπε, το διορθώνουμε.

Στείλε μήνυμα από τις Ρυθμίσεις → Υποστήριξη με τον αριθμό της χρέωσης, για να τη βρούμε γρήγορα.', 'billing', 50, array['επιστροφη χρηματων', 'refund', 'να μου επιστρεψετε', 'χρεωθηκα λαθος', 'λαθος χρεωση', 'διπλη χρεωση']::text[], true),
  ('what-are-credits', 'en', 'What are credits?', 'Credits are what you spend on AI work: a chat message, building a website, an agent run.

Every plan includes a monthly allowance that renews, and you can buy extra packs if you run out sooner. Credits from a pack do not expire at the end of the month — they stay on the account until you use them.

How much each plan includes is on the pricing page.', 'credits', 10, array['what are credits', 'credits', 'what is a credit', 'how do credits work', 'credit system']::text[], true),
  ('what-are-credits', 'el', 'Τι είναι τα credits;', 'Τα credits είναι αυτό που ξοδεύεις για τις ενέργειες AI: ένα μήνυμα στο chat, μια δημιουργία website, μια εκτέλεση agent.

Κάθε πλάνο δίνει ένα μηνιαίο απόθεμα που ανανεώνεται, και μπορείς να αγοράσεις έξτρα πακέτα αν τελειώσουν νωρίτερα. Τα credits από πακέτο δεν λήγουν στο τέλος του μήνα — μένουν στον λογαριασμό μέχρι να τα χρησιμοποιήσεις.

Πόσα δίνει το κάθε πλάνο θα το δεις στη σελίδα τιμών.', 'credits', 10, array['τι ειναι τα credits', 'τι ειναι credits', 'credits', 'μοναδες', 'what are credits', 'πως δουλευουν τα credits']::text[], true),
  ('what-are-credits', 'es', '¿Qué son los créditos?', 'Los créditos son lo que gastas cuando trabaja la IA: un mensaje en el chat, la creación de un sitio web, la ejecución de un agente.

Cada plan trae una cantidad mensual que se renueva, y puedes comprar paquetes extra si se te acaban antes de tiempo. Los créditos de un paquete no caducan a final de mes — se quedan en tu cuenta hasta que los uses.

Cuántos incluye cada plan lo verás en la página de Precios.', 'credits', 10, array['que son los creditos', 'creditos', 'que es un credito', 'como funcionan los creditos', 'para que sirven los creditos', 'sistema de creditos', 'en que se gastan los creditos']::text[], true),
  ('what-are-credits', 'fr', 'Que sont les crédits ?', 'Les crédits, c''est ce que vous dépensez pour le travail de l''IA : un message dans la discussion, la génération d''un site web, une exécution d''agent.

Chaque forfait comprend une réserve mensuelle qui se renouvelle, et vous pouvez acheter des packs supplémentaires si elle s''épuise avant. Les crédits d''un pack n''expirent pas à la fin du mois — ils restent sur le compte jusqu''à ce que vous les utilisiez.

Ce que comprend chaque forfait est indiqué sur la page Tarifs.', 'credits', 10, array['c est quoi les credits', 'les credits c est quoi', 'credits', 'a quoi servent les credits', 'comment marchent les credits', 'comment fonctionnent les credits', 'systeme de credits']::text[], true),
  ('what-are-credits', 'de', 'Was sind Credits?', 'Credits sind das, was du für die Arbeit der KI ausgibst: eine Nachricht im Chat, das Erstellen einer Website, ein Agentenlauf.

In jedem Tarif steckt ein monatliches Guthaben, das sich immer wieder erneuert, und wenn es früher zur Neige geht, kaufst du einfach ein zusätzliches Paket dazu. Credits aus einem Paket verfallen am Monatsende nicht — sie bleiben auf deinem Konto, bis du sie verbrauchst.

Wie viel in welchem Tarif enthalten ist, steht auf der Preisseite.', 'credits', 10, array['was sind credits', 'credits', 'was ist ein credit', 'wie funktionieren credits', 'wofur sind credits', 'credits erklarung', 'guthaben']::text[], true),
  ('what-are-credits', 'it', 'Che cosa sono i crediti?', 'I crediti sono quello che spendi per il lavoro dell''IA: un messaggio in chat, la generazione di un sito, l''esecuzione di un agente.

Ogni piano include una quantità mensile che si rinnova, e se finiscono prima puoi acquistare pacchetti extra. I crediti di un pacchetto non scadono a fine mese — restano sull''account finché non li usi.

Quanti ne include ogni piano lo trovi sulla pagina Prezzi.', 'credits', 10, array['cosa sono i crediti', 'che cosa sono i crediti', 'crediti', 'come funzionano i crediti', 'a cosa servono i crediti', 'sistema di crediti', 'cos e un credito']::text[], true),
  ('what-are-credits', 'pt', 'O que são os créditos?', 'Os créditos são o que gastas em trabalho de IA: uma mensagem no chat, a criação de um site, a execução de um agente.

Cada plano inclui uma quantidade mensal que se renova, e podes comprar pacotes extra se acabarem mais cedo. Os créditos de um pacote não expiram no fim do mês — ficam na conta até os usares.

Quanto inclui cada plano está na página Preços.', 'credits', 10, array['o que sao creditos', 'creditos', 'o que e um credito', 'como funcionam os creditos', 'para que servem os creditos']::text[], true),
  ('what-are-credits', 'zh', '额度是什么？', '额度是你为 AI 工作花掉的东西：一条聊天消息、生成一个网站、运行一次智能体。

每个方案都包含每月自动恢复的额度，用得快的话也可以另外购买额度包。额度包里的额度不会在月末失效——会一直留在账户里，直到你用完为止。

每个方案包含多少，请看定价页面。', 'credits', 10, array['额度是什么', '什么是额度', '额度', '点数', '额度怎么用', '额度规则']::text[], true),
  ('what-are-credits', 'ja', 'クレジットとは何ですか？', 'クレジットは AI の処理に使う残高です。チャットの一通、ウェブサイトの生成、エージェントの一回の実行などで消費します。

どのプランにも毎月更新される割り当てが含まれており、早く使い切った場合は追加パックを購入できます。パックで購入したクレジットは月末に失効しません。使い切るまでアカウントに残ります。

各プランに含まれる量は料金ページをご覧ください。', 'credits', 10, array['クレジットとは', 'クレジット', '残高とは', 'クレジットの仕組み', '何に使う']::text[], true),
  ('what-are-credits', 'ar', 'ما هو الرصيد؟', 'الرصيد هو ما تُنفقه على عمل الذكاء الاصطناعي: رسالة في المحادثة، أو إنشاء موقع، أو تشغيل وكيل.

كل خطة تتضمن حصة شهرية تتجدد، ويمكنك شراء حزم إضافية إذا نفدت مبكرًا. رصيد الحزمة لا ينتهي في آخر الشهر، بل يبقى في الحساب حتى تستخدمه.

حصة كل خطة موجودة في صفحة الأسعار.', 'credits', 10, array['ما هو الرصيد', 'الرصيد', 'ما معنى الرصيد', 'كيف يعمل الرصيد', 'النقاط']::text[], true),
  ('credit-cost-per-action', 'en', 'How many credits does each action cost?', 'There is no fixed price per action. The charge is worked out from the real cost of each call, so a short message costs less than a long one.

Before anything expensive you see an estimate, and once it finishes you see the actual charge in your history.', 'credits', 20, array['how many credits does it cost', 'credit cost', 'cost per action', 'how much is charged', 'how many credits', 'credits per message']::text[], true),
  ('credit-cost-per-action', 'el', 'Πόσα credits κοστίζει κάθε ενέργεια;', 'Η χρέωση δεν είναι σταθερή ανά ενέργεια — υπολογίζεται από το πραγματικό κόστος της κάθε κλήσης, οπότε ένα σύντομο μήνυμα κοστίζει λιγότερο από ένα μεγάλο.

Πριν από κάθε ακριβή ενέργεια βλέπεις εκτίμηση, και μετά την ολοκλήρωση βλέπεις την πραγματική χρέωση στο ιστορικό σου.', 'credits', 20, array['ποσα credits κοστιζει', 'ποσο χρεωνει', 'ποσα credits χρειαζονται', 'χρεωση ανα', 'how many credits', 'credit cost']::text[], true),
  ('credits-ran-out', 'en', 'I have run out of credits — what now?', 'Two options: wait for the next monthly renewal, or buy a credit pack that is added immediately.

Pack credits do not expire at the end of the month, so nothing you buy is lost at the next renewal. Both options are in Settings → Billing.', 'credits', 30, array['ran out of credits', 'no credits left', 'out of credits', 'buy credits', 'how do i buy credits', 'need more credits', 'credits finished']::text[], true),
  ('credits-ran-out', 'el', 'Τελείωσαν τα credits μου — τι κάνω;', 'Δύο επιλογές: περιμένεις την επόμενη μηνιαία ανανέωση, ή αγοράζεις ένα πακέτο credits που προστίθεται αμέσως.

Τα credits του πακέτου δεν λήγουν στο τέλος του μήνα, οπότε τίποτα από όσα αγοράζεις δεν χάνεται στην επόμενη ανανέωση. Και τα δύο γίνονται από τις Ρυθμίσεις → Χρέωση.', 'credits', 30, array['τελειωσαν τα credits', 'δεν εχω credits', 'εξαντληθηκαν', 'ran out of credits', 'πως αγοραζω credits', 'να παρω credits', 'θελω κι αλλα credits']::text[], true),
  ('credits-ran-out', 'es', 'Me he quedado sin créditos, ¿y ahora qué?', 'Dos opciones: esperar a la renovación del mes que viene, o comprar un paquete de créditos, que se añade al momento.

Los créditos del paquete no caducan a final de mes, así que nada de lo que compres se pierde en la siguiente renovación. Las dos cosas se hacen desde Configuración → Facturación.', 'credits', 30, array['me he quedado sin creditos', 'no me quedan creditos', 'sin creditos', 'comprar creditos', 'como compro creditos', 'necesito mas creditos', 'se me han acabado los creditos', 'recargar creditos']::text[], true),
  ('credits-ran-out', 'fr', 'Je n''ai plus de crédits — je fais quoi ?', 'Deux possibilités : attendre le prochain renouvellement mensuel, ou acheter un pack de crédits qui s''ajoute immédiatement.

Les crédits d''un pack n''expirent pas à la fin du mois : rien de ce que vous achetez n''est perdu au renouvellement suivant. Les deux se font dans Paramètres → Facturation.', 'credits', 30, array['plus de credits', 'je n ai plus de credits', 'credits epuises', 'acheter des credits', 'comment acheter des credits', 'il me faut plus de credits', 'recharger des credits', 'credits termines']::text[], true),
  ('credits-ran-out', 'de', 'Meine Credits sind aufgebraucht — was jetzt?', 'Zwei Möglichkeiten: auf die nächste monatliche Erneuerung warten oder ein Credit-Paket kaufen, das sofort gutgeschrieben wird.

Die Credits aus einem Paket verfallen am Monatsende nicht, bei der nächsten Erneuerung geht dir also nichts davon verloren. Beides findest du unter Einstellungen → Abrechnung.', 'credits', 30, array['credits alle', 'keine credits mehr', 'credits aufgebraucht', 'credits nachkaufen', 'wie kaufe ich credits', 'credits aufladen', 'mehr credits', 'guthaben leer']::text[], true),
  ('credits-ran-out', 'it', 'Ho finito i crediti — e adesso?', 'Due possibilità: aspettare il rinnovo del mese prossimo, oppure acquistare un pacchetto di crediti, che si aggiunge subito.

I crediti del pacchetto non scadono a fine mese, quindi niente di quello che compri va perso al rinnovo successivo. Le fai entrambe da Impostazioni → Fatturazione.', 'credits', 30, array['ho finito i crediti', 'crediti finiti', 'non ho piu crediti', 'sono senza crediti', 'comprare crediti', 'come compro i crediti', 'mi servono piu crediti', 'ricaricare i crediti']::text[], true),
  ('credits-ran-out', 'pt', 'Fiquei sem créditos — e agora?', 'Duas opções: esperar pela renovação mensal seguinte, ou comprar um pacote de créditos que é adicionado de imediato.

Os créditos do pacote não expiram no fim do mês, por isso nada do que compras se perde na renovação seguinte. Ambas as opções estão em Configurações → Faturação.', 'credits', 30, array['fiquei sem creditos', 'acabaram os creditos', 'nao tenho creditos', 'comprar creditos', 'como compro creditos', 'preciso de mais creditos']::text[], true),
  ('credits-ran-out', 'zh', '额度用完了怎么办？', '两个选择：等下个月自动恢复，或者购买额度包，购买后立即到账。

额度包里的额度不会在月末失效，所以你买的部分不会在下次恢复时被清掉。两种方式都在「设置 → 账单」里。', 'credits', 30, array['额度用完了', '没额度了', '额度不够', '怎么买额度', '购买额度', '充值']::text[], true),
  ('credits-ran-out', 'ja', 'クレジットがなくなりました。どうすればいいですか？', '方法は二つあります。翌月の更新を待つか、すぐに反映されるクレジットパックを購入するかです。

パックのクレジットは月末に失効しないため、購入した分が次の更新で消えることはありません。どちらも「設定 → 請求」から行えます。', 'credits', 30, array['クレジットがない', 'クレジット切れ', '残高不足', 'クレジットを買う', '購入したい', '追加したい']::text[], true),
  ('credits-ran-out', 'ar', 'نفد رصيدي، ماذا أفعل؟', 'أمامك خياران: انتظار التجديد الشهري التالي، أو شراء حزمة رصيد تُضاف فورًا.

رصيد الحزمة لا ينتهي في آخر الشهر، فلا يضيع شيء مما تشتريه عند التجديد التالي. كلا الخيارين في الإعدادات ← الفوترة.', 'credits', 30, array['نفد الرصيد', 'ما عندي رصيد', 'الرصيد خلص', 'شراء رصيد', 'كيف اشتري رصيد', 'اريد رصيد']::text[], true),
  ('credits-rollover', 'en', 'Do credits carry over to the next month?', 'Your plan''s monthly credits renew each month and do not accumulate.

Credits you buy in a pack are different: they stay on your account until you spend them, through renewals, plan changes and cancellation alike.', 'credits', 40, array['carry over', 'rollover', 'do credits expire', 'credits expire', 'unused credits', 'accumulate']::text[], true),
  ('credits-rollover', 'el', 'Μεταφέρονται τα credits στον επόμενο μήνα;', 'Τα μηνιαία credits του πλάνου ανανεώνονται κάθε μήνα και δεν συσσωρεύονται.

Τα credits που αγοράζεις σε πακέτο είναι διαφορετικά: μένουν στον λογαριασμό σου μέχρι να τα ξοδέψεις — σε ανανεώσεις, σε αλλαγές πλάνου και σε ακύρωση.', 'credits', 40, array['μεταφερονται', 'rollover', 'χανονται τα credits', 'συσσωρευονται', 'expire credits', 'ληγουν τα credits']::text[], true),
  ('create-website', 'en', 'How do I build a website?', 'Open Website Builder from the side menu, describe in plain words what you want — what your business does, who it is for, what style you like — and press create.

You can upload reference images too, such as a logo or product photos, and it will follow your style. When it is ready you publish it to its own address with one click.', 'websites', 10, array['how do i build a website', 'how do i make a website', 'create website', 'build website', 'i want a site', 'website builder', 'make me a site']::text[], true),
  ('create-website', 'el', 'Πώς φτιάχνω website;', 'Πήγαινε στο Website Builder από το πλαϊνό μενού, γράψε με απλά λόγια τι θέλεις — τι κάνει η επιχείρησή σου, σε ποιον απευθύνεται, τι ύφος θες — και πάτα δημιουργία.

Μπορείς να ανεβάσεις και εικόνες αναφοράς, λογότυπο ή φωτογραφίες προϊόντων, για να ακολουθήσει το στυλ σου. Όταν είναι έτοιμο, το δημοσιεύεις σε δική του διεύθυνση με ένα κλικ.', 'websites', 10, array['πως φτιαχνω website', 'πως φτιαχνω ιστοσελιδα', 'δημιουργια website', 'create website', 'θελω ενα site', 'website builder', 'ιστοσελιδα']::text[], true),
  ('create-website', 'es', '¿Cómo hago un sitio web?', 'Abre el Generador de Sitios en el menú lateral, cuenta con tus palabras qué quieres —a qué se dedica tu negocio, a quién se dirige, qué estilo te gusta— y dale a crear.

También puedes subir imágenes de referencia, como el logo o fotos de tus productos, y seguirá tu estilo. Cuando esté listo, lo publicas en su propia dirección con un clic.', 'websites', 10, array['como hago una web', 'crear una web', 'hacer una pagina web', 'generador de sitios', 'quiero una web', 'crear sitio web', 'necesito una pagina', 'montar una web']::text[], true),
  ('create-website', 'fr', 'Comment créer un site web ?', 'Ouvrez le Générateur de Site dans le menu latéral, décrivez avec vos mots ce que vous voulez — ce que fait votre activité, à qui elle s''adresse, le style qui vous plaît — puis cliquez sur Générer le Site.

Vous pouvez aussi importer des images de référence, un logo ou des photos de produits par exemple, et il suivra votre style. Quand le site est prêt, vous le publiez à sa propre adresse en un clic.', 'websites', 10, array['comment faire un site', 'creer un site', 'faire un site web', 'je veux un site', 'generer un site', 'generateur de site', 'comment creer un site internet', 'site vitrine']::text[], true),
  ('create-website', 'de', 'Wie baue ich eine Website?', 'Öffne im Seitenmenü den Website-Builder, beschreibe mit eigenen Worten, was du willst — was dein Unternehmen macht, für wen es da ist, welcher Stil dir gefällt — und klick auf „Website Generieren“.

Du kannst auch Referenzbilder hochladen, ein Logo oder Produktfotos zum Beispiel, dann richtet sich die KI nach deinem Stil. Ist die Website fertig, veröffentlichst du sie mit einem Klick unter einer eigenen Adresse.', 'websites', 10, array['wie baue ich eine website', 'website erstellen', 'webseite bauen', 'homepage erstellen', 'website builder', 'brauche eine website', 'internetseite erstellen', 'seite erstellen lassen']::text[], true),
  ('create-website', 'it', 'Come creo un sito web?', 'Apri il Generatore di Siti dal menu laterale, racconta con parole tue che cosa vuoi — di che cosa si occupa la tua attività, a chi si rivolge, che stile ti piace — e premi Genera Sito.

Puoi anche caricare immagini di riferimento, il logo o le foto dei prodotti, così segue il tuo stile. Quando è pronto lo pubblichi al suo indirizzo con un clic.', 'websites', 10, array['come creo un sito', 'come faccio un sito', 'creare un sito web', 'voglio un sito', 'generatore di siti', 'fare una pagina web', 'sito internet', 'come si crea un sito']::text[], true),
  ('create-website', 'pt', 'Como crio um site?', 'Abre o Gerador de Sites no menu lateral, descreve por palavras simples o que queres — o que faz o teu negócio, a quem se dirige, que estilo gostas — e carrega em criar.

Também podes carregar imagens de referência, como o logótipo ou fotografias de produtos, e ele segue o teu estilo. Quando estiver pronto, publicas num endereço próprio com um clique.', 'websites', 10, array['como crio um site', 'como faco um website', 'criar site', 'criar website', 'quero um site', 'gerador de sites', 'fazer uma pagina']::text[], true),
  ('create-website', 'zh', '怎么做网站？', '在侧边菜单打开网站生成器，用大白话写清楚你想要什么——你的业务是做什么的、面向谁、想要什么风格——然后点击创建。

你也可以上传参考图片，比如标志或产品照片，它会照着你的风格来。做好之后，一键就能发布到独立网址上。', 'websites', 10, array['怎么做网站', '怎么建网站', '创建网站', '生成网站', '我想要个网站', '网站生成器']::text[], true),
  ('create-website', 'ja', 'ウェブサイトはどう作りますか？', 'サイドメニューからウェブサイトビルダーを開き、どんなサイトにしたいかを普通の言葉で書いてください。事業の内容、対象となるお客様、好みの雰囲気などです。書けたら作成を押します。

ロゴや商品写真などの参考画像をアップロードすると、その雰囲気に合わせて作られます。完成したら、ワンクリックで専用のアドレスに公開できます。', 'websites', 10, array['サイトを作りたい', 'ウェブサイトの作り方', 'ホームページ', 'サイト作成', 'ウェブサイトビルダー', '作り方']::text[], true),
  ('create-website', 'ar', 'كيف أُنشئ موقعًا؟', 'افتح منشئ المواقع من القائمة الجانبية، واكتب بكلمات بسيطة ما تريده: ماذا يعمل نشاطك، ولمن، وأي أسلوب تفضّل، ثم اضغط إنشاء.

يمكنك أيضًا رفع صور مرجعية مثل الشعار أو صور المنتجات فيسير على أسلوبك. وعندما يجهز، تنشره على عنوان خاص به بنقرة واحدة.', 'websites', 10, array['كيف اعمل موقع', 'انشاء موقع', 'اريد موقع', 'بناء موقع', 'منشئ المواقع', 'صفحة الكترونية']::text[], true),
  ('publish-website', 'en', 'How do I publish my website?', 'In Website Builder, open the site and press Publish. You choose a name for the address and the site goes live straight away.

Every publish is kept as a version, so you can go back to an earlier one whenever you need to.', 'websites', 20, array['how do i publish', 'publish', 'go live', 'put it online', 'publish site', 'make it public']::text[], true),
  ('publish-website', 'el', 'Πώς δημοσιεύω το website μου;', 'Από το Website Builder, άνοιξε το site και πάτα Δημοσίευση. Διαλέγεις ένα όνομα για τη διεύθυνση και το site γίνεται αμέσως ζωντανό.

Κάθε δημοσίευση κρατιέται σαν έκδοση, οπότε μπορείς να γυρίσεις πίσω σε προηγούμενη όποτε χρειαστεί.', 'websites', 20, array['πως δημοσιευω', 'publish', 'να το ανεβασω', 'live site', 'δημοσιευση site', 'να βγει στον αερα']::text[], true),
  ('create-agent', 'en', 'How do I create an agent?', 'In the Agents menu, describe in one sentence what you want it to do and how often — for example "every morning send me a summary of news in my industry".

Ionexa builds the agent for you, runs it on schedule and sends you the result. You can pause it or change it whenever you like.', 'agents', 10, array['how do i create an agent', 'create agent', 'build an agent', 'automation', 'agents', 'i want an agent', 'schedule a task']::text[], true),
  ('create-agent', 'el', 'Πώς φτιάχνω agent;', 'Στο μενού Agents, περίγραψε σε μία πρόταση τι θέλεις να κάνει και κάθε πότε — π.χ. «κάθε πρωί στείλε μου περίληψη των νέων του κλάδου μου».

Το Ionexa φτιάχνει τον agent μόνο του, τον τρέχει στην ώρα του και σου στέλνει το αποτέλεσμα. Μπορείς να τον σταματήσεις ή να τον αλλάξεις όποτε θες.', 'agents', 10, array['πως φτιαχνω agent', 'δημιουργια agent', 'create agent', 'αυτοματοποιηση', 'agents', 'θελω εναν agent', 'προγραμματισμενη εργασια']::text[], true),
  ('create-agent', 'es', '¿Cómo creo un agente?', 'En el menú Agentes IA, describe en una frase qué quieres que haga y cada cuánto — por ejemplo «cada mañana mándame un resumen de las noticias de mi sector».

Ionexa te monta el agente, lo ejecuta a su hora y te envía el resultado. Puedes pausarlo o cambiarlo cuando quieras.', 'agents', 10, array['como creo un agente', 'crear agente', 'agentes', 'quiero un agente', 'automatizar', 'automatizacion', 'tarea programada', 'programar una tarea']::text[], true),
  ('create-agent', 'fr', 'Comment créer un agent ?', 'Dans le menu Agents IA, décrivez en une phrase ce que l''agent doit faire et à quelle fréquence — par exemple « chaque matin, envoie-moi un résumé de l''actualité de mon secteur ».

Ionexa construit l''agent à votre place, l''exécute selon son planning et vous envoie le résultat. Vous pouvez le mettre en pause ou le modifier quand vous voulez.', 'agents', 10, array['comment creer un agent', 'creer un agent', 'faire un agent', 'agent ia', 'je veux un agent', 'automatiser une tache', 'tache planifiee', 'agents']::text[], true),
  ('create-agent', 'de', 'Wie erstelle ich einen Agenten?', 'Im Menü KI-Agenten beschreibst du in einem Satz, was er tun soll und wie oft — zum Beispiel „schick mir jeden Morgen eine Zusammenfassung der Nachrichten aus meiner Branche“.

Ionexa baut den Agenten für dich, lässt ihn nach Zeitplan laufen und schickt dir das Ergebnis. Du kannst ihn jederzeit pausieren oder ändern.', 'agents', 10, array['agent erstellen', 'wie erstelle ich einen agenten', 'ki agent', 'agenten', 'automatisierung', 'aufgabe automatisieren', 'agent einrichten', 'taglich automatisch']::text[], true),
  ('create-agent', 'it', 'Come creo un agente?', 'Nel menu Agenti IA descrivi in una frase che cosa deve fare e ogni quanto — per esempio «ogni mattina mandami un riassunto delle notizie del mio settore».

Ionexa costruisce l''agente al posto tuo, lo esegue secondo la pianificazione e ti manda il risultato. Puoi metterlo in pausa o modificarlo quando vuoi.', 'agents', 10, array['come creo un agente', 'creare un agente', 'agenti', 'agente ia', 'voglio un agente', 'automatizzare', 'automazione', 'attivita programmata']::text[], true),
  ('create-agent', 'pt', 'Como crio um agente?', 'No menu Agentes de IA, descreve numa frase o que queres que ele faça e com que frequência — por exemplo «todas as manhãs envia-me um resumo das notícias do meu setor».

O Ionexa constrói o agente por ti, executa-o à hora certa e envia-te o resultado. Podes pausá-lo ou alterá-lo quando quiseres.', 'agents', 10, array['como crio um agente', 'criar agente', 'agentes', 'automatizar', 'quero um agente', 'tarefa automatica', 'agendar tarefa']::text[], true),
  ('create-agent', 'zh', '怎么创建智能体？', '在「AI 智能体」菜单里，用一句话说清楚你要它做什么、多久做一次——比如「每天早上给我发一份我这个行业的新闻摘要」。

Ionexa 会替你把智能体建好，按时运行，并把结果发给你。你随时可以暂停或修改。', 'agents', 10, array['怎么创建智能体', '创建智能体', '智能体', '自动化', '我想要个智能体', '定时任务']::text[], true),
  ('create-agent', 'ja', 'エージェントはどう作りますか？', '「AI エージェント」メニューで、何をどのくらいの頻度でしてほしいかを一文で書いてください。たとえば「毎朝、自分の業界のニュースの要約を送って」といった具合です。

Ionexa がエージェントを組み立て、時間どおりに実行し、結果をお届けします。停止も変更もいつでもできます。', 'agents', 10, array['エージェントの作り方', 'エージェントを作る', 'エージェント', '自動化', '定期実行', 'スケジュール']::text[], true),
  ('create-agent', 'ar', 'كيف أُنشئ وكيلًا؟', 'من قائمة وكلاء الذكاء الاصطناعي، اكتب في جملة واحدة ما تريده أن يفعل وكل كم مرة — مثلًا: «كل صباح أرسل لي ملخص أخبار مجالي».

يبني Ionexa الوكيل نيابة عنك، ويُشغّله في موعده، ويرسل لك النتيجة. ويمكنك إيقافه أو تعديله متى شئت.', 'agents', 10, array['كيف اعمل وكيل', 'انشاء وكيل', 'الوكلاء', 'اتمتة', 'اريد وكيل', 'مهمة تلقائية']::text[], true),
  ('create-mission', 'en', 'How do I create a mission?', 'In Mission Control you write a goal the way you would say it to a person — "I want more customers by spring".

Ionexa breaks it into concrete steps, and from there you can work through them yourself or hand some of them to an agent.', 'missions', 10, array['how do i create a mission', 'mission control', 'goal', 'goals', 'create mission', 'missions', 'plan a goal']::text[], true),
  ('create-mission', 'el', 'Πώς φτιάχνω mission;', 'Στο Mission Control γράφεις έναν στόχο όπως θα τον έλεγες σε άνθρωπο — «θέλω περισσότερους πελάτες μέχρι την άνοιξη».

Το Ionexa τον σπάει σε συγκεκριμένα βήματα, και μετά μπορείς να τα δουλέψεις μόνος σου ή να αναθέσεις κάποια σε agent.', 'missions', 10, array['πως φτιαχνω mission', 'mission control', 'στοχος', 'στοχους', 'create mission', 'missions', 'σχεδιο δρασης']::text[], true),
  ('create-mission', 'es', '¿Cómo creo una misión?', 'En Centro de Misión escribes un objetivo tal como se lo dirías a una persona: «quiero más clientes para la primavera».

Ionexa lo divide en pasos concretos, y a partir de ahí puedes trabajarlos tú o encargar alguno a un agente.', 'missions', 10, array['como creo una mision', 'crear mision', 'misiones', 'centro de mision', 'objetivo', 'objetivos', 'plan de accion']::text[], true),
  ('create-mission', 'fr', 'Comment créer une mission ?', 'Dans Contrôle de Mission, vous écrivez un objectif comme vous le diriez à quelqu''un : « je veux plus de clients d''ici le printemps ».

Ionexa le découpe en étapes concrètes, et vous pouvez ensuite les traiter vous-même ou en confier certaines à un agent.', 'missions', 10, array['comment creer une mission', 'creer une mission', 'missions', 'controle de mission', 'objectif', 'objectifs', 'plan d action']::text[], true),
  ('create-mission', 'de', 'Wie erstelle ich eine Mission?', 'In der Missionskontrolle schreibst du ein Ziel so auf, wie du es einem Menschen sagen würdest: «ich will bis zum Frühjahr mehr Kunden».

Ionexa zerlegt es in konkrete Schritte, und danach arbeitest du sie selbst ab oder gibst einzelne an einen Agenten ab.', 'missions', 10, array['wie erstelle ich eine mission', 'mission erstellen', 'missionen', 'missionskontrolle', 'ziel', 'ziele', 'aktionsplan']::text[], true),
  ('create-mission', 'it', 'Come creo una missione?', 'Nel Centro Missioni scrivi un obiettivo come lo diresti a una persona: «voglio più clienti entro la primavera».

Ionexa lo scompone in passaggi concreti, e da lì puoi seguirli tu oppure affidarne qualcuno a un agente.', 'missions', 10, array['come creo una missione', 'creare una missione', 'missioni', 'centro missioni', 'obiettivo', 'obiettivi', 'piano d azione']::text[], true),
  ('create-mission', 'pt', 'Como crio uma missão?', 'No Controle de Missão escreves um objetivo como o dirias a uma pessoa: «quero mais clientes até à primavera».

O Ionexa divide-o em passos concretos e, a partir daí, podes trabalhá-los tu ou entregar alguns a um agente.', 'missions', 10, array['como crio uma missao', 'criar missao', 'missoes', 'controle de missao', 'objetivo', 'objetivos', 'plano de acao']::text[], true),
  ('create-mission', 'zh', '怎么创建任务？', '在任务控制中心，用你对人说话的方式写下目标——比如「我想在春天前多一些客户」。

Ionexa 会把它拆成具体步骤，之后你可以自己去做，也可以把其中几步交给智能体。', 'missions', 10, array['怎么创建任务', '创建任务', '任务', '任务控制中心', '目标', '定目标', '行动计划']::text[], true),
  ('create-mission', 'ja', 'ミッションはどう作りますか？', 'ミッションコントロールで、人に話すのと同じ言葉で目標を書いてください。たとえば「春までにお客様を増やしたい」といった具合です。

Ionexa がそれを具体的な手順に分解します。あとはご自身で進めても、いくつかをエージェントに任せてもかまいません。', 'missions', 10, array['ミッションの作り方', 'ミッションを作る', 'ミッション', 'ミッションコントロール', '目標', '計画', 'やることを分ける']::text[], true),
  ('create-mission', 'ar', 'كيف أُنشئ مهمة؟', 'في مركز التحكم بالمهام تكتب هدفك كما تقوله لشخص: «أريد عملاء أكثر قبل الربيع».

يقسّمه Ionexa إلى خطوات محددة، ثم تنفذها بنفسك أو تُسند بعضها إلى وكيل.', 'missions', 10, array['كيف انشئ مهمة', 'انشاء مهمة', 'المهام', 'مركز التحكم بالمهام', 'هدف', 'اهداف', 'خطة عمل']::text[], true),
  ('chat-memory', 'en', 'Does the chat remember previous conversations?', 'Within a single conversation it always remembers what was said earlier.

Between conversations it keeps only lasting, useful facts — your name, what you do, your preferences — and that is available on paid plans. You can see everything it has kept, and delete any of it, in Settings → Memory.', 'chat', 10, array['does it remember', 'memory', 'remember', 'previous conversations', 'forgets', 'does not remember', 'chat history']::text[], true),
  ('chat-memory', 'el', 'Θυμάται το chat προηγούμενες συνομιλίες;', 'Μέσα στην ίδια συνομιλία θυμάται πάντα τα προηγούμενα μηνύματα.

Ανάμεσα σε διαφορετικές συνομιλίες κρατά μόνο μόνιμα χρήσιμα στοιχεία — όνομα, επάγγελμα, προτιμήσεις — και αυτό υπάρχει στα επί πληρωμή πλάνα. Μπορείς να δεις ό,τι έχει κρατήσει, και να το σβήσεις, από τις Ρυθμίσεις → Μνήμη.', 'chat', 10, array['θυμαται', 'μνημη', 'memory', 'προηγουμενες συνομιλιες', 'ξεχναει', 'δεν θυμαται', 'ιστορικο συνομιλιων']::text[], true),
  ('chat-memory', 'es', '¿El chat recuerda conversaciones anteriores?', 'Dentro de una misma conversación siempre recuerda lo que se dijo antes.

Entre conversaciones distintas guarda solo datos duraderos y útiles —tu nombre, a qué te dedicas, tus preferencias— y eso está disponible en los planes de pago. Puedes ver todo lo que ha guardado, y borrar lo que quieras, en Configuración → Memoria AI.', 'chat', 10, array['se acuerda', 'memoria', 'recuerda conversaciones', 'conversaciones anteriores', 'se olvida', 'no recuerda nada', 'historial de chat']::text[], true),
  ('chat-memory', 'fr', 'Le chat se souvient-il des conversations précédentes ?', 'Au sein d''une même conversation, il se souvient toujours de ce qui a été dit avant.

D''une conversation à l''autre, il ne garde que des informations durables et utiles — votre nom, votre métier, vos préférences — et cette fonction est réservée aux formules payantes. Vous pouvez voir tout ce qu''il a retenu, et le supprimer, dans Paramètres → Mémoire IA.', 'chat', 10, array['il se souvient', 'memoire', 'conversations precedentes', 'il oublie', 'ne se souvient pas', 'historique des discussions', 'garde t il']::text[], true),
  ('chat-memory', 'de', 'Merkt sich der Chat frühere Unterhaltungen?', 'Innerhalb einer Unterhaltung merkt er sich immer, was vorher gesagt wurde.

Über Unterhaltungen hinweg behält er nur dauerhaft Nützliches — deinen Namen, was du machst, deine Vorlieben — und das gibt es in den kostenpflichtigen Tarifen. Du kannst alles Gespeicherte ansehen und löschen unter Einstellungen → KI-Gedächtnis.', 'chat', 10, array['merkt er sich', 'gedachtnis', 'fruhere unterhaltungen', 'vergisst', 'erinnert sich nicht', 'chatverlauf', 'speichert er']::text[], true),
  ('chat-memory', 'it', 'La chat ricorda le conversazioni precedenti?', 'All''interno della stessa conversazione ricorda sempre quello che è stato detto prima.

Tra una conversazione e l''altra conserva solo informazioni durature e utili — il tuo nome, di cosa ti occupi, le tue preferenze — ed è disponibile nei piani a pagamento. Puoi vedere tutto quello che ha conservato, ed eliminarlo, in Impostazioni → Memoria AI.', 'chat', 10, array['si ricorda', 'memoria', 'conversazioni precedenti', 'dimentica', 'non ricorda', 'cronologia chat', 'conserva']::text[], true),
  ('chat-memory', 'pt', 'O chat lembra-se de conversas anteriores?', 'Dentro da mesma conversa lembra-se sempre do que foi dito antes.

Entre conversas diferentes guarda apenas informação duradoura e útil — o teu nome, o que fazes, as tuas preferências — e isso está disponível nos planos pagos. Podes ver tudo o que guardou, e apagar, em Configurações → Memória IA.', 'chat', 10, array['lembra se', 'memoria', 'conversas anteriores', 'esquece', 'nao se lembra', 'historico de conversas', 'guarda']::text[], true),
  ('chat-memory', 'zh', '聊天会记得之前的对话吗？', '在同一个对话里，它始终记得前面说过的内容。

跨对话时，它只保留长期有用的信息——你的名字、你做什么、你的偏好——这项功能在付费方案中提供。你可以在「设置 → AI 记忆」里查看它记住的全部内容，也可以随时删除。', 'chat', 10, array['会记得吗', '记忆', '记得之前', '之前的对话', '会忘记吗', '不记得', '聊天记录']::text[], true),
  ('chat-memory', 'ja', 'チャットは前の会話を覚えていますか？', '同じ会話の中では、前に話した内容を常に覚えています。

会話をまたぐ場合は、長く役立つ情報だけを保持します。お名前、お仕事、好みなどです。この機能は有料プランでご利用いただけます。保持している内容は「設定 → AI メモリー」からすべて確認でき、削除もできます。', 'chat', 10, array['覚えている', 'メモリー', '前の会話', '忘れる', '覚えていない', 'チャット履歴', '記憶']::text[], true),
  ('chat-memory', 'ar', 'هل تتذكر المحادثة ما دار سابقًا؟', 'داخل المحادثة الواحدة تتذكر دائمًا ما قيل قبل ذلك.

أما بين المحادثات فتحتفظ فقط بالمعلومات الدائمة المفيدة — اسمك، وما تعمل، وتفضيلاتك — وهذه الميزة متاحة في الخطط المدفوعة. ويمكنك الاطلاع على كل ما احتفظت به وحذفه من الإعدادات ← ذاكرة الذكاء الاصطناعي.', 'chat', 10, array['هل تتذكر', 'الذاكرة', 'المحادثات السابقة', 'تنسى', 'لا تتذكر', 'سجل المحادثات', 'تحتفظ']::text[], true),
  ('upload-files', 'en', 'Can I upload files?', 'Yes — PDF, Word, Excel, CSV, plain text and Markdown. Upload them in Files, Ionexa reads their contents, and then you can ask questions about them.

Your files are private: nobody else has access, and every download goes through a temporary link.', 'files', 10, array['upload a file', 'upload', 'pdf', 'files', 'documents', 'can i upload', 'attach a file', 'read my document']::text[], true),
  ('upload-files', 'el', 'Μπορώ να ανεβάσω αρχεία;', 'Ναι — PDF, Word, Excel, CSV, κείμενο και Markdown. Τα ανεβάζεις στο Files, το Ionexa διαβάζει το περιεχόμενό τους και μετά μπορείς να κάνεις ερωτήσεις πάνω σε αυτά.

Τα αρχεία σου είναι ιδιωτικά: κανείς άλλος δεν έχει πρόσβαση και κάθε κατέβασμα γίνεται με προσωρινό σύνδεσμο.', 'files', 10, array['ανεβασω αρχειο', 'upload', 'pdf', 'αρχεια', 'files', 'εγγραφα', 'να διαβασεις το αρχειο μου']::text[], true),
  ('upload-files', 'es', '¿Puedo subir archivos?', 'Sí — PDF, Word, Excel, CSV, texto plano y Markdown. Los subes en Archivos, Ionexa lee lo que hay dentro y a partir de ahí le preguntas lo que quieras sobre ellos.

Tus archivos son privados: nadie más tiene acceso y cada descarga se hace con un enlace temporal.', 'files', 10, array['subir un archivo', 'subir archivos', 'pdf', 'archivos', 'documentos', 'puedo subir', 'adjuntar archivo', 'que lea mi documento']::text[], true),
  ('upload-files', 'fr', 'Puis-je importer des fichiers ?', 'Oui — PDF, Word, Excel, CSV, texte et Markdown. Vous les importez dans Fichiers, Ionexa lit leur contenu, et ensuite vous pouvez poser vos questions dessus.

Vos fichiers sont privés : personne d''autre n''y a accès, et chaque téléchargement passe par un lien temporaire.', 'files', 10, array['importer un fichier', 'envoyer un fichier', 'uploader un fichier', 'pdf', 'fichiers', 'documents', 'je peux importer des fichiers', 'lire mon document']::text[], true),
  ('upload-files', 'de', 'Kann ich Dateien hochladen?', 'Ja — PDF, Word, Excel, CSV, einfacher Text und Markdown. Du lädst sie unter Dateien hoch, Ionexa liest ihren Inhalt, und danach kannst du Fragen dazu stellen.

Deine Dateien bleiben privat: Sonst hat niemand Zugriff darauf, und jeder Download läuft über einen zeitlich begrenzten Link.', 'files', 10, array['datei hochladen', 'dateien hochladen', 'pdf hochladen', 'kann ich dateien hochladen', 'dokumente', 'pdf lesen lassen', 'unterlagen hochladen', 'dateien']::text[], true),
  ('upload-files', 'it', 'Posso caricare dei file?', 'Sì — PDF, Word, Excel, CSV, testo e Markdown. Li carichi nella sezione File, Ionexa ne legge il contenuto e poi puoi fargli tutte le domande che vuoi su quello che c''è dentro.

I tuoi file sono privati: nessun altro può accedervi e ogni download passa da un link temporaneo.', 'files', 10, array['caricare un file', 'caricare file', 'posso caricare file', 'pdf', 'file', 'documenti', 'allegare un file', 'far leggere un documento']::text[], true),
  ('upload-files', 'pt', 'Posso carregar ficheiros?', 'Sim — PDF, Word, Excel, CSV, texto simples e Markdown. Carrega-os em Ficheiros, o Ionexa lê o conteúdo e depois podes fazer perguntas sobre eles.

Os teus ficheiros são privados: mais ninguém tem acesso e cada descarga passa por uma ligação temporária.', 'files', 10, array['carregar ficheiro', 'enviar ficheiro', 'upload', 'pdf', 'ficheiros', 'documentos', 'ler o meu documento']::text[], true),
  ('upload-files', 'zh', '可以上传文件吗？', '可以——PDF、Word、Excel、CSV、纯文本和 Markdown。在「文件」里上传，Ionexa 会读取内容，之后你就可以针对这些内容提问。

你的文件是私有的：别人无法访问，每次下载都通过临时链接完成。', 'files', 10, array['可以上传文件吗', '上传文件', '上传', '文件', '文档', '读我的文件']::text[], true),
  ('upload-files', 'ja', 'ファイルをアップロードできますか？', 'はい。PDF、Word、Excel、CSV、テキスト、Markdown に対応しています。「ファイル」からアップロードすると Ionexa が中身を読み取り、その内容について質問できるようになります。

ファイルは非公開です。ほかの人がアクセスすることはなく、ダウンロードはその都度、一時的なリンク経由で行われます。', 'files', 10, array['ファイルをアップロード', 'アップロード', 'pdf', 'ファイル', '書類', '資料を読ませたい']::text[], true),
  ('upload-files', 'ar', 'هل يمكنني رفع ملفات؟', 'نعم — PDF وWord وExcel وCSV والنص العادي وMarkdown. ارفعها في الملفات، فيقرأ Ionexa محتواها، ثم يمكنك أن تسأل عنها.

ملفاتك خاصة: لا يصل إليها أحد غيرك، وكل تنزيل يمر عبر رابط مؤقت.', 'files', 10, array['رفع ملف', 'ارفع ملف', 'الملفات', 'مستندات', 'هل يمكن رفع', 'اقرا ملفي']::text[], true),
  ('connect-gmail', 'en', 'How do I connect Gmail or Google Drive?', 'Settings → Connections. Pick the service and approve access in Google''s own window.

You see exactly what it will read before you approve, and you can disconnect whenever you want — the access keys are deleted immediately when you do.', 'integrations', 10, array['gmail', 'google drive', 'connect', 'integration', 'integrations', 'how do i connect', 'link my email']::text[], true),
  ('connect-gmail', 'el', 'Πώς συνδέω Gmail ή Google Drive;', 'Ρυθμίσεις → Συνδέσεις. Διαλέγεις την υπηρεσία και εγκρίνεις την πρόσβαση στο παράθυρο της Google.

Βλέπεις ακριβώς τι θα διαβάζει πριν το εγκρίνεις, και μπορείς να αποσυνδέσεις όποτε θες — τότε τα κλειδιά πρόσβασης διαγράφονται αμέσως.', 'integrations', 10, array['gmail', 'google drive', 'συνδεση', 'integration', 'slack', 'πως συνδεω', 'connect', 'συνδεσεις']::text[], true),
  ('connect-gmail', 'es', '¿Cómo conecto Gmail o Google Drive?', 'Configuración → Integraciones. Eliges el servicio y apruebas el acceso en la propia ventana de Google.

Ves exactamente qué va a leer antes de aprobarlo, y puedes desconectar cuando quieras: al hacerlo las claves de acceso se borran de inmediato.', 'integrations', 10, array['gmail', 'google drive', 'conectar', 'integraciones', 'como conecto', 'vincular correo', 'conexiones']::text[], true),
  ('connect-gmail', 'fr', 'Comment connecter Gmail ou Google Drive ?', 'Paramètres → Intégrations. Vous choisissez le service et vous autorisez l''accès dans la fenêtre de Google.

Vous voyez exactement ce qui sera lu avant d''autoriser, et vous pouvez vous déconnecter quand vous voulez — les clés d''accès sont alors supprimées immédiatement.', 'integrations', 10, array['gmail', 'google drive', 'connecter', 'integrations', 'comment connecter', 'relier ma boite mail', 'connexions']::text[], true),
  ('connect-gmail', 'de', 'Wie verbinde ich Gmail oder Google Drive?', 'Einstellungen → Integrationen. Du wählst den Dienst und bestätigst den Zugriff im Fenster von Google.

Du siehst vor dem Bestätigen genau, was gelesen wird, und kannst jederzeit trennen — die Zugangsschlüssel werden dann sofort gelöscht.', 'integrations', 10, array['gmail', 'google drive', 'verbinden', 'integrationen', 'wie verbinde ich', 'mail verknupfen', 'verbindungen']::text[], true),
  ('connect-gmail', 'it', 'Come collego Gmail o Google Drive?', 'Impostazioni → Integrazioni. Scegli il servizio e approvi l''accesso nella finestra di Google.

Vedi esattamente cosa leggerà prima di approvare, e puoi scollegare quando vuoi: le chiavi di accesso vengono cancellate subito.', 'integrations', 10, array['gmail', 'google drive', 'collegare', 'integrazioni', 'come collego', 'collegare la posta', 'collegamenti']::text[], true),
  ('connect-gmail', 'pt', 'Como ligo o Gmail ou o Google Drive?', 'Configurações → Integrações. Escolhes o serviço e aprovas o acesso na própria janela da Google.

Vês exatamente o que vai ler antes de aprovares, e podes desligar quando quiseres — as chaves de acesso são apagadas de imediato.', 'integrations', 10, array['gmail', 'google drive', 'ligar', 'integracoes', 'como ligo', 'ligar o email', 'ligacoes']::text[], true),
  ('connect-gmail', 'zh', '怎么连接 Gmail 或 Google Drive？', '设置 → 集成。选好服务，然后在谷歌自己的窗口里授权。

授权之前你会看到它到底会读取什么，而且随时可以断开——断开时访问密钥会立即删除。', 'integrations', 10, array['gmail', '谷歌网盘', '怎么连接', '集成', '连接邮箱', '授权', '绑定账号']::text[], true),
  ('connect-gmail', 'ja', 'Gmail や Google ドライブはどう連携しますか？', '設定 → 連携から、サービスを選んで Google の画面でアクセスを承認してください。

承認する前に何を読み取るかがはっきり表示され、いつでも解除できます。解除するとアクセスキーはその場で削除されます。', 'integrations', 10, array['gmail', 'グーグルドライブ', '連携', '接続', 'どう連携', 'メールをつなぐ', '外部サービス']::text[], true),
  ('connect-gmail', 'ar', 'كيف أربط Gmail أو Google Drive؟', 'الإعدادات ← التكاملات. تختار الخدمة وتوافق على الوصول في نافذة Google نفسها.

ترى بالضبط ما سيُقرأ قبل الموافقة، ويمكنك فصل الربط متى شئت — وعندها تُحذف مفاتيح الوصول فورًا.', 'integrations', 10, array['gmail', 'جوجل درايف', 'ربط', 'التكاملات', 'كيف اربط', 'ربط البريد', 'الاتصالات']::text[], true),
  ('password-reset', 'en', 'I forgot my password.', 'On the sign-in page press "Forgot my password" and enter your email address. A reset link will be sent to you.

If it does not arrive, check your spam folder.', 'account', 10, array['forgot my password', 'password', 'reset password', 'cannot log in', 'cant sign in', 'locked out', 'change password']::text[], true),
  ('password-reset', 'el', 'Ξέχασα τον κωδικό μου.', 'Στη σελίδα σύνδεσης πάτα «Ξέχασα τον κωδικό μου» και βάλε το email σου. Θα σου έρθει σύνδεσμος επαναφοράς.

Αν δεν φτάνει, κοίτα και στα ανεπιθύμητα.', 'account', 10, array['ξεχασα τον κωδικο', 'password', 'reset password', 'επαναφορα κωδικου', 'δεν μπορω να μπω', 'αλλαγη κωδικου']::text[], true),
  ('invite-code', 'en', 'Where do I enter an invite code?', 'There is a field for it on the sign-up form.

If you already have an account, enter it in Settings → Account. Whatever it grants is applied to your account as soon as it goes through.', 'account', 20, array['invite code', 'beta code', 'referral code', 'where do i enter the code', 'promo code', 'invitation']::text[], true),
  ('invite-code', 'el', 'Πού βάζω τον κωδικό πρόσκλησης;', 'Στη φόρμα εγγραφής υπάρχει πεδίο για κωδικό πρόσκλησης.

Αν έχεις ήδη λογαριασμό, τον καταχωρείς από τις Ρυθμίσεις → Λογαριασμός. Μόλις περάσει, τα προνόμια που δίνει ενεργοποιούνται αμέσως στον λογαριασμό σου.', 'account', 20, array['κωδικος προσκλησης', 'invite code', 'beta code', 'κωδικο beta', 'που βαζω τον κωδικο', 'προσκληση']::text[], true),
  ('team-members', 'en', 'Can I add people from my team?', 'Yes, on the plans that include a team. Go to Settings → Team, invite by email, and that person joins the same workspace.

Which plans include it, and how many seats they give, is on the pricing page.', 'account', 30, array['team', 'add people', 'colleagues', 'invite a member', 'collaboration', 'multiple users', 'seats']::text[], true),
  ('team-members', 'el', 'Μπορώ να προσθέσω άτομα από την ομάδα μου;', 'Ναι, στα πλάνα που περιλαμβάνουν ομάδα. Ρυθμίσεις → Ομάδα, προσκαλείς με email και το άτομο μπαίνει στον ίδιο χώρο εργασίας.

Ποια πλάνα το έχουν και πόσες θέσεις δίνουν θα το δεις στη σελίδα τιμών.', 'account', 30, array['ομαδα', 'team', 'συνεργατες', 'προσκληση μελους', 'collaboration', 'χρηστες', 'πολλοι χρηστες']::text[], true),
  ('notifications', 'en', 'How do I manage notifications?', 'Settings → Notifications. Email and phone notifications are controlled separately, and so is each type — agent results, reminders, low credits.

Critical security notifications cannot be switched off.', 'account', 40, array['notifications', 'email notifications', 'push notifications', 'stop emailing me', 'turn off notifications', 'alerts']::text[], true),
  ('notifications', 'el', 'Πώς ρυθμίζω τις ειδοποιήσεις;', 'Ρυθμίσεις → Ειδοποιήσεις. Ξεχωριστά για email και για ειδοποιήσεις στο κινητό, και ανά τύπο — αποτελέσματα agent, υπενθυμίσεις, χαμηλά credits.

Οι κρίσιμες ειδοποιήσεις ασφαλείας δεν απενεργοποιούνται.', 'account', 40, array['ειδοποιησεις', 'notifications', 'email ειδοποιησεις', 'push', 'να μη μου στελνετε', 'απενεργοποιηση ειδοποιησεων']::text[], true),
  ('contact-support', 'en', 'How do I reach a human?', 'Settings → Support, and write to us.

If it is about a charge, include the charge reference so we can find it quickly.', 'account', 50, array['contact', 'support', 'human', 'talk to someone', 'contact support', 'help from a person', 'customer service']::text[], true),
  ('contact-support', 'el', 'Πώς επικοινωνώ με άνθρωπο;', 'Ρυθμίσεις → Υποστήριξη, και γράψε μας.

Αν το θέμα αφορά χρέωση, βάλε και τον αριθμό της χρέωσης για να το βρούμε γρήγορα.', 'account', 50, array['επικοινωνια', 'support', 'ανθρωπο', 'υποστηριξη', 'contact', 'να μιλησω με καποιον', 'εξυπηρετηση']::text[], true),
  ('contact-support', 'es', '¿Cómo hablo con una persona?', 'Configuración → Soporte, y escríbenos.

Si es por un cobro, añade la referencia del cobro y lo localizamos enseguida.', 'account', 50, array['contacto', 'soporte', 'hablar con una persona', 'atencion al cliente', 'contactar', 'ayuda de una persona', 'quiero hablar con alguien', 'escribir a soporte']::text[], true),
  ('contact-support', 'fr', 'Comment joindre une vraie personne ?', 'Paramètres → Assistance, et écrivez-nous.

S''il s''agit d''un paiement, indiquez la référence de la transaction pour qu''on la retrouve tout de suite.', 'account', 50, array['contacter le support', 'parler a quelqu un', 'assistance', 'support', 'aide humaine', 'service client', 'joindre quelqu un', 'contact']::text[], true),
  ('contact-support', 'de', 'Wie erreiche ich einen Menschen?', 'Einstellungen → Support, und schreib uns.

Wenn es um eine Abbuchung geht, gib die Zahlungsreferenz mit an — dann finden wir sie schnell.', 'account', 50, array['support kontaktieren', 'kundenservice', 'mit einem menschen sprechen', 'hilfe von einem menschen', 'kontakt', 'support', 'wie erreiche ich euch', 'jemanden erreichen']::text[], true),
  ('contact-support', 'it', 'Come parlo con una persona?', 'Impostazioni → Supporto, e scrivici.

Se si tratta di un addebito, aggiungi il riferimento dell''addebito così lo troviamo subito.', 'account', 50, array['contatto', 'assistenza', 'supporto', 'parlare con una persona', 'voglio parlare con qualcuno', 'contattare l assistenza', 'servizio clienti', 'aiuto da una persona']::text[], true),
  ('contact-support', 'pt', 'Como falo com uma pessoa?', 'Configurações → Suporte, e escreve-nos.

Se for sobre uma cobrança, inclui a referência da cobrança para a encontrarmos depressa.', 'account', 50, array['contacto', 'suporte', 'falar com alguem', 'apoio ao cliente', 'ajuda de uma pessoa', 'atendimento']::text[], true),
  ('contact-support', 'zh', '怎么联系人工？', '设置 → 支持，然后给我们留言。

如果是关于扣费的问题，请附上扣费单号，方便我们尽快查到。', 'account', 50, array['联系人工', '客服', '联系客服', '找人工', '技术支持', '怎么联系你们']::text[], true),
  ('contact-support', 'ja', '担当者に問い合わせるには？', '設定 → サポートから、ご連絡ください。

お支払いに関する内容であれば、請求の参照番号を添えていただけるとすぐにお調べできます。', 'account', 50, array['問い合わせ', 'サポート', '人に聞きたい', '連絡先', '担当者', 'カスタマーサポート']::text[], true),
  ('contact-support', 'ar', 'كيف أتواصل مع شخص؟', 'الإعدادات ← الدعم، واكتب لنا.

وإن كان الأمر يخص عملية دفع، أضف رقم العملية لنعثر عليها بسرعة.', 'account', 50, array['تواصل', 'الدعم', 'خدمة العملاء', 'اكلم شخص', 'الدعم الفني', 'كيف اتواصل']::text[], true),
  ('data-privacy', 'en', 'What do you do with my data?', 'Your data is yours. We do not sell it, we do not use it to train models, and every account sees only its own — that is enforced in the database, not just in the application.

You can download it or delete it whenever you want.', 'privacy', 10, array['my data', 'privacy', 'data protection', 'security', 'do you sell my data', 'train models', 'gdpr', 'is my data safe']::text[], true),
  ('data-privacy', 'el', 'Τι κάνετε με τα δεδομένα μου;', 'Τα δεδομένα σου είναι δικά σου. Δεν τα πουλάμε, δεν τα χρησιμοποιούμε για εκπαίδευση μοντέλων, και κάθε λογαριασμός βλέπει μόνο τα δικά του — αυτό επιβάλλεται στη βάση, όχι μόνο στην εφαρμογή.

Μπορείς να τα κατεβάσεις ή να τα διαγράψεις όποτε θες.', 'privacy', 10, array['δεδομενα μου', 'ιδιωτικοτητα', 'privacy', 'ασφαλεια', 'τα πουλατε', 'εκπαιδευση μοντελων', 'gdpr', 'προστασια δεδομενων']::text[], true),
  ('data-privacy', 'es', '¿Qué hacéis con mis datos?', 'Tus datos son tuyos. No los vendemos, no los usamos para entrenar modelos y cada cuenta ve solo los suyos — eso se impone en la base de datos, no solo en la aplicación.

Puedes descargarlos o borrarlos cuando quieras.', 'privacy', 10, array['mis datos', 'privacidad', 'proteccion de datos', 'seguridad', 'vendeis mis datos', 'entrenar modelos', 'rgpd', 'gdpr', 'estan seguros mis datos']::text[], true),
  ('data-privacy', 'fr', 'Que faites-vous de mes données ?', 'Vos données vous appartiennent. Nous ne les vendons pas, nous ne nous en servons pas pour entraîner des modèles, et chaque compte ne voit que les siennes — c''est verrouillé dans la base de données, pas seulement dans l''application.

Vous pouvez les télécharger ou les supprimer quand vous voulez.', 'privacy', 10, array['mes donnees', 'confidentialite', 'vie privee', 'securite des donnees', 'vous vendez mes donnees', 'entrainement des modeles', 'rgpd', 'protection des donnees']::text[], true),
  ('data-privacy', 'de', 'Was macht ihr mit meinen Daten?', 'Deine Daten gehören dir. Wir verkaufen sie nicht, wir trainieren damit keine Modelle, und jedes Konto sieht ausschließlich seine eigenen — dafür sorgt die Datenbank selbst, nicht nur die Anwendung.

Du kannst sie jederzeit herunterladen oder löschen.', 'privacy', 10, array['meine daten', 'datenschutz', 'dsgvo', 'sind meine daten sicher', 'was passiert mit meinen daten', 'daten verkaufen', 'modelle trainieren', 'datensicherheit']::text[], true),
  ('data-privacy', 'it', 'Che cosa fate con i miei dati?', 'I tuoi dati sono tuoi. Non li vendiamo, non li usiamo per addestrare modelli e ogni account vede solo i propri — ed è imposto nel database, non soltanto nell''applicazione.

Puoi scaricarli o eliminarli quando vuoi.', 'privacy', 10, array['i miei dati', 'privacy', 'protezione dei dati', 'sicurezza dei dati', 'vendete i miei dati', 'addestrare i modelli', 'gdpr', 'i miei dati sono al sicuro']::text[], true),
  ('data-privacy', 'pt', 'O que fazem com os meus dados?', 'Os teus dados são teus. Não os vendemos, não os usamos para treinar modelos e cada conta vê apenas os seus — isso é imposto na base de dados, não só na aplicação.

Podes descarregá-los ou apagá-los quando quiseres.', 'privacy', 10, array['os meus dados', 'privacidade', 'protecao de dados', 'seguranca', 'vendem os meus dados', 'treinar modelos', 'rgpd']::text[], true),
  ('data-privacy', 'zh', '你们会怎么处理我的数据？', '你的数据是你的。我们不出售数据，不用它训练模型，每个账户只能看到自己的数据——这一点是在数据库层面强制执行的，不只是在应用里。

你随时可以下载或删除。', 'privacy', 10, array['我的数据', '隐私', '数据安全', '安全吗', '会卖我的数据吗', '训练模型', '数据保护']::text[], true),
  ('data-privacy', 'ja', 'データはどう扱われますか？', 'データはお客様のものです。販売しません。モデルの学習にも使いません。各アカウントは自分のデータだけを参照できます。これはアプリケーションだけでなくデータベース側で強制しています。

ダウンロードも削除も、いつでも可能です。', 'privacy', 10, array['データの扱い', 'プライバシー', '個人情報', '安全ですか', 'データを売る', '学習に使う']::text[], true),
  ('data-privacy', 'ar', 'ماذا تفعلون ببياناتي؟', 'بياناتك ملكك. لا نبيعها، ولا نستخدمها لتدريب النماذج، وكل حساب يرى بياناته وحدها — وهذا مفروض في قاعدة البيانات نفسها لا في التطبيق فقط.

ويمكنك تنزيلها أو حذفها متى شئت.', 'privacy', 10, array['بياناتي', 'الخصوصية', 'حماية البيانات', 'الامان', 'هل تبيعون البيانات', 'تدريب النماذج']::text[], true),
  ('export-data', 'en', 'Can I download my data?', 'Yes. Settings → Account → Export data.

You get a file with everything you have created — conversations, missions, websites, files, billing history. Access keys for connected accounts are left out for security reasons.', 'privacy', 20, array['download my data', 'export', 'export data', 'data export', 'copy of my data', 'take my data']::text[], true),
  ('export-data', 'el', 'Μπορώ να κατεβάσω τα δεδομένα μου;', 'Ναι. Ρυθμίσεις → Λογαριασμός → Εξαγωγή δεδομένων.

Παίρνεις ένα αρχείο με όλα όσα έχεις δημιουργήσει — συνομιλίες, missions, websites, αρχεία, ιστορικό χρεώσεων. Τα κλειδιά πρόσβασης των συνδεδεμένων λογαριασμών εξαιρούνται για λόγους ασφάλειας.', 'privacy', 20, array['κατεβασω τα δεδομενα', 'export', 'εξαγωγη', 'αντιγραφο δεδομενων', 'εξαγωγη δεδομενων']::text[], true),
  ('delete-account', 'en', 'How do I delete my account?', 'Settings → Account → Delete account. You will be asked to confirm, and then everything goes: conversations, files, websites, agents, history. It cannot be undone.

If you want a copy first, export your data from the same page.', 'privacy', 30, array['delete my account', 'delete account', 'close my account', 'remove my account', 'erase my account']::text[], true),
  ('delete-account', 'el', 'Πώς διαγράφω τον λογαριασμό μου;', 'Ρυθμίσεις → Λογαριασμός → Διαγραφή λογαριασμού. Θα σου ζητηθεί επιβεβαίωση, και μετά διαγράφονται όλα: συνομιλίες, αρχεία, websites, agents, ιστορικό. Δεν είναι αναστρέψιμο.

Αν θέλεις πρώτα αντίγραφο, κατέβασε τα δεδομένα σου από την ίδια σελίδα.', 'privacy', 30, array['διαγραφη λογαριασμου', 'delete account', 'να σβησω τον λογαριασμο', 'κλεισιμο λογαριασμου', 'διαγραφη προφιλ']::text[], true)

on conflict (slug, locale) do update
  set title      = excluded.title,
      body       = excluded.body,
      category   = excluded.category,
      "order"    = excluded."order",
      triggers   = excluded.triggers,
      published  = excluded.published,
      updated_at = now();

-- 7. What landed -----------------------------------------------------------------
-- Run this after the migration. It should return one row per locale, and
-- the English count must be the largest — English is the base, and a locale
-- with MORE articles than English means a slug exists that nothing falls
-- back to.
--
-- select locale, count(*) as articles
--   from public.help_articles
--  where published
--  group by locale
--  order by count(*) desc, locale;
