-- PUBLIC COULD EXECUTE A SECURITY DEFINER FUNCTION.
--
-- FOUND BY RUNNING scripts/tests/role-grants.dbtest.mjs, 2026-09-13,
-- against a local Postgres built from bootstrap-supabase.sql plus every
-- migration. It failed on one line:
--
--     FAIL  every holding is on the named list
--           PUBLIC EXECUTE on function public.prune_project_links()
--
-- and the catalogue agreed: proacl carried `=X/postgres`, which is the
-- spelling of "PUBLIC may EXECUTE". PUBLIC includes anon.
--
-- WHY IT MATTERS MORE THAN AN ORDINARY GRANT. prune_project_links is
-- `security definer` — it runs with the definer's privileges, so row
-- level security does not apply to what it deletes. A SECURITY DEFINER
-- function that PUBLIC may call is the shape privilege escalation takes;
-- that the body is scoped by `old.user_id` is a second line of defence,
-- not a reason to leave the first one open.
--
-- WHY IT IS NOT EXPLOITABLE AS IT STANDS, stated so nobody reads this as
-- a live incident: the function returns `trigger` and takes no arguments,
-- so a direct call raises "can only be called as a trigger". The defect
-- is the grant, and a grant that is wrong today is a grant that is wrong
-- when the function changes shape.
--
-- EVERY COMPARABLE FUNCTION IN THIS SCHEMA ALREADY DOES THIS. The
-- baseline revokes PUBLIC on reserve_credits, settle_reservation,
-- release_reservation, release_expired_reservations, record_site_view and
-- prune_integration_sync_log — the last of which is the same kind of
-- trigger sweeper as this one. 20261001000000_projects.sql created the
-- function and did not carry the line.
--
-- Postgres grants EXECUTE to PUBLIC on every new function by default,
-- which is why this has to be said rather than assumed.

revoke all on function public.prune_project_links() from public;

-- AND FROM authenticated, WHICH IS THE HALF I GOT WRONG FIRST.
--
-- The first draft of this migration revoked PUBLIC and then granted
-- EXECUTE to `authenticated, service_role`, on the reasoning that the end
-- state should be readable here. Running
-- scripts/tests/grants-and-policies.dbtest.mjs said otherwise:
--
--     FAIL  only the 9 argued-for functions are callable by a signed-in
--           user (13)
--           unexpected: ... prune_project_links
--
-- That gate's rule is the right one: a signed-in user may call a short,
-- deliberate list directly, and everything else goes through a server
-- route on the service role, which is where the "who is asking" check
-- lives. A TRIGGER function needs neither — it runs as part of the DELETE
-- on public.projects, under the table owner, and is never invoked by
-- name. Granting it to `authenticated` added a database entry point to
-- the browser in the act of closing one.
--
-- service_role keeps EXECUTE only because it owns nothing here and the
-- trigger fires under its writes too.
revoke all on function public.prune_project_links() from authenticated;
grant execute on function public.prune_project_links() to service_role;


-- ----------------------------------------------------------------------
-- AND A CORRECTION, IN THE SAME FILE THAT CARRIED THE MISTAKE
-- ----------------------------------------------------------------------
--
-- An earlier draft of THIS migration also contained:
--
--     revoke all on function public.chat_memory_prunable(integer, integer)
--       from authenticated;
--     revoke all on function public.prune_chat_memory(integer, integer)
--       from authenticated;
--
-- Both lines were WRONG and both are removed. The reasoning behind them
-- was that grants-and-policies.dbtest.mjs listed the two as callable by a
-- signed-in user without being argued for, and a grep appeared to show
-- that only src/lib/health/schema-canaries.ts named them — read by
-- /api/health, which uses createAdminClient(). The conclusion drawn was
-- "surface with no user behind it". That conclusion was false.
--
-- BOTH ARE CALLED FROM THE BROWSER, with the user's own client:
--
--   src/components/memory/ai-memory-list.tsx:108
--     supabase.rpc("prune_chat_memory")            <- the Forget button,
--     behind a window.confirm, on a client built by @/lib/supabase/client
--
--   src/app/dashboard/ai-memory/page.tsx:58
--     supabase.rpc("chat_memory_prunable")         <- the count shown
--     BEFORE the button is pressed, on the user's server-side session
--
-- Revoking those grants would have broken the Forget control and the
-- count beside it, for every user, the moment this file was pasted into
-- the SQL editor. That is the whole hazard this repository's first
-- working rule exists for: a migration is applied by hand, so a wrong one
-- waits silently until somebody runs it.
--
-- prune_chat_memory is `security invoker` ON PURPOSE — it deletes as the
-- caller, so RLS scopes it to that person's own rows — and its own
-- migration says why it must never be swept by a cron: "nothing deletes a
-- remembered fact without somebody pressing a button." Both functions
-- keep their grants, and grants-and-policies.dbtest.mjs now argues for
-- all three rather than revoking two of them.
