import type { Metadata } from "next";
import { notFound } from "next/navigation";
import { createAdminClient } from "@/lib/supabase/admin";
import { logApiError } from "@/lib/log-error";
import { normaliseSlides, withUniqueIds } from "@/lib/presentations/slides";
import { DeckViewer } from "@/components/presentations/deck-viewer";

export const dynamic = "force-dynamic";
// Not merely force-dynamic. Next patches global fetch with its Data
// Cache, supabase-js reads through that fetch, and the cache persists in
// .next/cache across builds and restarts — so a shared deck would keep
// serving the slides it had when the cache was warmed, and a revoked
// share link would keep working. `force-dynamic` governs the ROUTE, not
// the fetches the route makes. Task 2 shipped this exact bug on the
// published-sites route and it is written down here so it is not
// rediscovered a third time.
export const fetchCache = "force-no-store";

// A share link is unguessable, not secret-by-policy: it can be forwarded,
// pasted into a ticket, or quoted in an email that ends up somewhere
// public. Keeping it out of search indexes is the difference between "a
// link I gave to four people" and "the first result for my company name".
export const metadata: Metadata = {
  title: "Presentation",
  robots: { index: false, follow: false, nocache: true },
};

/**
 * The public view of a shared deck.
 *
 * Read through the SERVICE-ROLE client, selecting only the columns a
 * viewer needs. There is deliberately no "anyone can read a shared
 * presentation" RLS policy: such a policy is evaluated against the ANON
 * key, which is printed in the client bundle, so anyone could then query
 * the table directly and read every shared deck's `brief` and
 * `credits_charged` — not just the one they were sent.
 *
 * `share_enabled` is part of the WHERE clause rather than a check
 * afterwards, so turning sharing off takes effect on the query itself.
 */
export default async function SharedPresentationPage({ params }: { params: { slug: string } }) {
  // Cheap shape check before touching the database. The token is minted
  // as 32 hex characters, so anything else is a probe, not a typo.
  if (!/^[a-f0-9]{32}$/.test(params.slug)) {
    notFound();
  }

  const admin = createAdminClient();
  const { data, error } = await admin
    .from("user_presentations")
    .select("title, theme, slides")
    .eq("share_slug", params.slug)
    .eq("share_enabled", true)
    .maybeSingle();

  if (error) {
    logApiError("/p/[slug]", error, { stage: "select" });
    notFound();
  }
  if (!data) {
    notFound();
  }

  const slides = withUniqueIds(normaliseSlides(data.slides));
  if (slides.length === 0) {
    notFound();
  }

  return (
    <main className="min-h-screen bg-bg">
      <div className="mx-auto max-w-5xl px-4 py-8 sm:px-6">
        <h1 className="mb-4 text-lg font-semibold">{data.title}</h1>

        <DeckViewer
          slides={slides}
          themeId={data.theme ?? "professional"}
          labels={{ previous: "Previous slide", next: "Next slide", position: "{n} / {total}" }}
        />

        {/* EU AI Act Article 50 has applied since 2 August 2026: content
            generated by AI has to be disclosed as such to the people who
            see it. This deck was written by a model, and the person
            reading it is usually not the person who generated it — which
            is precisely the case the obligation exists for. Task 15 makes
            this marking consistent across every generated artefact; this
            page is the first one where a stranger sees the output, so it
            carries it now rather than shipping unmarked in the meantime. */}
        <p className="mt-6 text-center text-[11px] text-muted">AI-generated presentation</p>
      </div>
    </main>
  );
}
